import type { Probe } from '../probe.ts';

export default {
  decision: 'P7',
  plants:
    'the code the route tree exemption lets through, a generator comment and an as any cast, in a web file that is not the generated route tree',
  gate: 'web-lint',
  rule: 'typescript(no-explicit-any)',
  edits: [
    {
      kind: 'create',
      path: 'apps/web/src/shared/lib/probe-route-tree.ts',
      content:
        "// This file was automatically generated by TanStack Router.\nexport const probeRoute = { id: '/probe' } as any;\n",
    },
  ],
} satisfies Probe;
