export type GitActionReason =
  | 'CHANGED_SINCE_LOOKED'
  | 'STALE_PREPARATION'
  | 'REQUEST_MISMATCH'
  | 'CHECKOUT_BUSY'
  | 'UNSUPPORTED_CONFIGURATION'
  | 'NON_FAST_FORWARD'
  | 'GIT_REJECTED'
  | 'DEADLINE_EXCEEDED'
  | 'OUTCOME_UNKNOWN'
  | 'PROCESS_GROUP_UNCONFIRMED';
