export const themeTokenFile = 'packages/theme/src/tokens.css';
export const mobileStyleFile = 'apps/mobile/src/app.css';
export const mobileMetroFile = 'apps/mobile/metro.config.cjs';
export const mobileGeneratedTypes = 'apps/mobile/src/config/uniwind-types.d.ts';

const blocks: Readonly<Record<string, readonly string[]>> = {
  '': ['@theme inline', '@layer theme'],
  '@layer theme': [':root'],
  ':root': ['@variant light', '@variant dark'],
};

export function themeTokensValid(source: string): boolean {
  const statements =
    /\s*(--[a-z][a-z0-9-]*\s*:[^;{}]+;|@theme\s+inline\s*\{|@layer\s+theme\s*\{|:root\s*\{|@variant\s+(?:light|dark)\s*\{|\})/gy;
  const stack: string[] = [];
  let offset = 0;
  while (offset < source.trimEnd().length) {
    statements.lastIndex = offset;
    const statement = statements.exec(source);
    if (statement === null) return false;
    const value = statement[1]?.trim() ?? '';
    const parent = stack.at(-1) ?? '';
    if (value === '}') {
      if (stack.pop() === undefined) return false;
    } else if (value.startsWith('--')) {
      if (
        !['@theme inline', ':root', '@variant light', '@variant dark'].includes(
          parent,
        ) ||
        /(?:url|expression)\s*\(|@|\/\*/i.test(value)
      )
        return false;
    } else {
      const block = value.slice(0, -1).trim().replace(/\s+/g, ' ');
      if (!blocks[parent]?.includes(block)) return false;
      stack.push(block);
    }
    offset = statements.lastIndex;
  }
  return stack.length === 0 && offset > 0;
}

const metroSource = `const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');
module.exports = withUniwindConfig(getDefaultConfig(__dirname), {
  cssEntryFile: './src/app.css',
  dtsFile: './src/config/uniwind-types.d.ts',
});`;

function compactSource(source: string): string {
  return source.match(/'[^'\n]*'|"[^"\n]*"|\/\/[^\n]*|[^\s]/g)?.join('') ?? '';
}

export function mobileMetroValid(source: string): boolean {
  return compactSource(source) === compactSource(metroSource);
}

export function mobileStylesValid(source: string): boolean {
  const imports: string[] = [];
  const tokens = source
    .replace(/@import\s+['"]([^'"]+)['"]\s*;/g, (_, specifier: string) => {
      imports.push(specifier);
      return '';
    })
    .trim();
  return (
    imports.join(',') === 'tailwindcss,uniwind,@porcelain/theme/tokens.css' &&
    (tokens === '' || themeTokensValid(tokens))
  );
}

const uniwindDeclaration = `// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />
declare module 'uniwind' {
  export interface UniwindConfig {
    themes: readonly ['light', 'dark']
  }
}
export {}`;

export function mobileGeneratedTypesValid(source: string): boolean {
  return compactSource(source) === compactSource(uniwindDeclaration);
}

export function themeManifestValid(manifest: unknown): boolean {
  if (typeof manifest !== 'object' || manifest === null) return false;
  return (
    Object.keys(manifest).toSorted().join(',') ===
      'exports,name,private,type' &&
    'name' in manifest &&
    manifest.name === '@porcelain/theme' &&
    'private' in manifest &&
    manifest.private === true &&
    'type' in manifest &&
    manifest.type === 'module' &&
    'exports' in manifest &&
    typeof manifest.exports === 'object' &&
    manifest.exports !== null &&
    Object.keys(manifest.exports).join(',') === './tokens.css' &&
    './tokens.css' in manifest.exports &&
    manifest.exports['./tokens.css'] === './src/tokens.css'
  );
}
