appId: com.fabiofiorita.porcelain.dev
name: Pair two environments that are online
---
- runFlow: connect.yaml
- runFlow: open-settings.yaml
- runFlow:
    file: add-environment.yaml
    env:
      PAIRING_LINK: ${FIRST_PAIRING_LINK}
      ENVIRONMENT_NAME: ${FIRST_ENVIRONMENT_NAME}
- runFlow:
    file: add-environment.yaml
    env:
      PAIRING_LINK: ${SECOND_PAIRING_LINK}
      ENVIRONMENT_NAME: ${SECOND_ENVIRONMENT_NAME}
