// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PairedRouteImport } from './routes/_paired';
import { Route as PairRouteImport } from './routes/pair';
import { Route as PairedIndexRouteImport } from './routes/_paired/index';
import { Route as PairedProjectIdWorktreeIdRouteImport } from './routes/_paired/$projectId/$worktreeId';
import { Route as PairedProjectIdWorktreeIdIndexRouteImport } from './routes/_paired/$projectId/$worktreeId/index';
import { Route as PairedProjectIdWorktreeIdSettingsRouteImport } from './routes/_paired/$projectId/$worktreeId/settings';

const PairedRoute = PairedRouteImport.update({
  id: '/_paired',
  getParentRoute: () => rootRouteImport,
} as any);
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any);
const PairedIndexRoute = PairedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PairedRoute,
} as any);
const PairedProjectIdWorktreeIdRoute =
  PairedProjectIdWorktreeIdRouteImport.update({
    id: '/$projectId/$worktreeId',
    path: '/$projectId/$worktreeId',
    getParentRoute: () => PairedRoute,
  } as any);
const PairedProjectIdWorktreeIdIndexRoute =
  PairedProjectIdWorktreeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PairedProjectIdWorktreeIdRoute,
  } as any);
const PairedProjectIdWorktreeIdSettingsRoute =
  PairedProjectIdWorktreeIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PairedProjectIdWorktreeIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PairedIndexRoute;
  '/pair': typeof PairRoute;
  '/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdRouteWithChildren;
  '/$projectId/$worktreeId/settings': typeof PairedProjectIdWorktreeIdSettingsRoute;
  '/$projectId/$worktreeId/': typeof PairedProjectIdWorktreeIdIndexRoute;
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute;
  '/': typeof PairedIndexRoute;
  '/$projectId/$worktreeId/settings': typeof PairedProjectIdWorktreeIdSettingsRoute;
  '/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_paired': typeof PairedRouteWithChildren;
  '/pair': typeof PairRoute;
  '/_paired/': typeof PairedIndexRoute;
  '/_paired/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdRouteWithChildren;
  '/_paired/$projectId/$worktreeId/settings': typeof PairedProjectIdWorktreeIdSettingsRoute;
  '/_paired/$projectId/$worktreeId/': typeof PairedProjectIdWorktreeIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/pair'
    | '/$projectId/$worktreeId'
    | '/$projectId/$worktreeId/settings'
    | '/$projectId/$worktreeId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/pair'
    | '/'
    | '/$projectId/$worktreeId/settings'
    | '/$projectId/$worktreeId';
  id:
    | '__root__'
    | '/_paired'
    | '/pair'
    | '/_paired/'
    | '/_paired/$projectId/$worktreeId'
    | '/_paired/$projectId/$worktreeId/settings'
    | '/_paired/$projectId/$worktreeId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PairedRoute: typeof PairedRouteWithChildren;
  PairRoute: typeof PairRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_paired': {
      id: '/_paired';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PairedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pair': {
      id: '/pair';
      path: '/pair';
      fullPath: '/pair';
      preLoaderRoute: typeof PairRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_paired/': {
      id: '/_paired/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PairedIndexRouteImport;
      parentRoute: typeof PairedRoute;
    };
    '/_paired/$projectId/$worktreeId': {
      id: '/_paired/$projectId/$worktreeId';
      path: '/$projectId/$worktreeId';
      fullPath: '/$projectId/$worktreeId';
      preLoaderRoute: typeof PairedProjectIdWorktreeIdRouteImport;
      parentRoute: typeof PairedRoute;
    };
    '/_paired/$projectId/$worktreeId/': {
      id: '/_paired/$projectId/$worktreeId/';
      path: '/';
      fullPath: '/$projectId/$worktreeId/';
      preLoaderRoute: typeof PairedProjectIdWorktreeIdIndexRouteImport;
      parentRoute: typeof PairedProjectIdWorktreeIdRoute;
    };
    '/_paired/$projectId/$worktreeId/settings': {
      id: '/_paired/$projectId/$worktreeId/settings';
      path: '/settings';
      fullPath: '/$projectId/$worktreeId/settings';
      preLoaderRoute: typeof PairedProjectIdWorktreeIdSettingsRouteImport;
      parentRoute: typeof PairedProjectIdWorktreeIdRoute;
    };
  }
}

interface PairedProjectIdWorktreeIdRouteChildren {
  PairedProjectIdWorktreeIdSettingsRoute: typeof PairedProjectIdWorktreeIdSettingsRoute;
  PairedProjectIdWorktreeIdIndexRoute: typeof PairedProjectIdWorktreeIdIndexRoute;
}

const PairedProjectIdWorktreeIdRouteChildren: PairedProjectIdWorktreeIdRouteChildren =
  {
    PairedProjectIdWorktreeIdSettingsRoute:
      PairedProjectIdWorktreeIdSettingsRoute,
    PairedProjectIdWorktreeIdIndexRoute: PairedProjectIdWorktreeIdIndexRoute,
  };

const PairedProjectIdWorktreeIdRouteWithChildren =
  PairedProjectIdWorktreeIdRoute._addFileChildren(
    PairedProjectIdWorktreeIdRouteChildren,
  );

interface PairedRouteChildren {
  PairedIndexRoute: typeof PairedIndexRoute;
  PairedProjectIdWorktreeIdRoute: typeof PairedProjectIdWorktreeIdRouteWithChildren;
}

const PairedRouteChildren: PairedRouteChildren = {
  PairedIndexRoute: PairedIndexRoute,
  PairedProjectIdWorktreeIdRoute: PairedProjectIdWorktreeIdRouteWithChildren,
};

const PairedRouteWithChildren =
  PairedRoute._addFileChildren(PairedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PairedRoute: PairedRouteWithChildren,
  PairRoute: PairRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
