// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PairedRouteImport } from './routes/_paired';
import { Route as PairRouteImport } from './routes/pair';
import { Route as PairedIndexRouteImport } from './routes/_paired/index';
import { Route as PairedProjectIdWorktreeIdRouteImport } from './routes/_paired/$projectId.$worktreeId';

const PairedRoute = PairedRouteImport.update({
  id: '/_paired',
  getParentRoute: () => rootRouteImport,
} as any);
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any);
const PairedIndexRoute = PairedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PairedRoute,
} as any);
const PairedProjectIdWorktreeIdRoute =
  PairedProjectIdWorktreeIdRouteImport.update({
    id: '/$projectId/$worktreeId',
    path: '/$projectId/$worktreeId',
    getParentRoute: () => PairedRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PairedIndexRoute;
  '/pair': typeof PairRoute;
  '/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdRoute;
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute;
  '/': typeof PairedIndexRoute;
  '/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_paired': typeof PairedRouteWithChildren;
  '/pair': typeof PairRoute;
  '/_paired/': typeof PairedIndexRoute;
  '/_paired/$projectId/$worktreeId': typeof PairedProjectIdWorktreeIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/pair' | '/$projectId/$worktreeId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/pair' | '/' | '/$projectId/$worktreeId';
  id:
    | '__root__'
    | '/_paired'
    | '/pair'
    | '/_paired/'
    | '/_paired/$projectId/$worktreeId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PairedRoute: typeof PairedRouteWithChildren;
  PairRoute: typeof PairRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_paired': {
      id: '/_paired';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PairedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pair': {
      id: '/pair';
      path: '/pair';
      fullPath: '/pair';
      preLoaderRoute: typeof PairRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_paired/': {
      id: '/_paired/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PairedIndexRouteImport;
      parentRoute: typeof PairedRoute;
    };
    '/_paired/$projectId/$worktreeId': {
      id: '/_paired/$projectId/$worktreeId';
      path: '/$projectId/$worktreeId';
      fullPath: '/$projectId/$worktreeId';
      preLoaderRoute: typeof PairedProjectIdWorktreeIdRouteImport;
      parentRoute: typeof PairedRoute;
    };
  }
}

interface PairedRouteChildren {
  PairedIndexRoute: typeof PairedIndexRoute;
  PairedProjectIdWorktreeIdRoute: typeof PairedProjectIdWorktreeIdRoute;
}

const PairedRouteChildren: PairedRouteChildren = {
  PairedIndexRoute: PairedIndexRoute,
  PairedProjectIdWorktreeIdRoute: PairedProjectIdWorktreeIdRoute,
};

const PairedRouteWithChildren =
  PairedRoute._addFileChildren(PairedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PairedRoute: PairedRouteWithChildren,
  PairRoute: PairRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
