import { z } from 'zod';

export const apiErrorSchema = z.object({
  code: z.enum([
    'UNSUPPORTED_GIT_FILTERS',
    'WORKTREE_NOT_FOUND',
    'WORKTREE_CHANGED',
    'INSPECTION_LIMIT',
    'UNSUPPORTED_PATH_ENCODING',
    'UNAUTHORIZED',
    'WORKTREE_NOT_FOUND',
    'INVALID_REQUEST',
    'WORKTREE_NOT_FOUND',
    'PATH_NOT_FOUND',
    'PATH_NOT_READABLE',
    'UNSUPPORTED_PATH',
    'UNSUPPORTED_TEXT',
    'FILE_TOO_LARGE',
    'DIRECTORY_TOO_LARGE',
    'CONTENT_CHANGED',
    'REPOSITORY_UNAVAILABLE',
    'SERVICE_UNAVAILABLE',
    'INTERNAL_ERROR',
    'HISTORY_SNAPSHOT_UNAVAILABLE',
    'READ_LIMIT_EXCEEDED',
    'UNSUPPORTED_HISTORY_DATA',
  ]),
  message: z.string(),
});
