import type { ProcedureKind } from './procedure-contract'
import type { ProcedureDomain } from './procedure-ledger'
import type { ProcedureName } from './procedures/names'

/**
 * Migration-only initial ownership baseline. CON-021 deletes this with the transitional ledger.
 * It is not a public wire catalog; the procedure lint uses it only to enforce migration ownership.
 */
export type InitialProcedureOwnership = Readonly<{
  domain: ProcedureDomain
  name: ProcedureName
  kind: ProcedureKind
}>

export const initialProcedureOwnershipBaseline = [
  { domain: 'remote', name: 'daemonInfo', kind: 'query' },
  { domain: 'remote', name: 'accessStatus', kind: 'query' },
  { domain: 'remote', name: 'issuePairingLink', kind: 'mutation' },
  { domain: 'remote', name: 'revokePairingLink', kind: 'mutation' },
  { domain: 'remote', name: 'revokeAuthorizedClient', kind: 'mutation' },
  { domain: 'remote', name: 'revokeCurrentClient', kind: 'mutation' },
  { domain: 'remote', name: 'tailnetStatus', kind: 'query' },
  { domain: 'remote', name: 'setTailnetBind', kind: 'mutation' },
  { domain: 'remote', name: 'lanStatus', kind: 'query' },
  { domain: 'remote', name: 'setLanBind', kind: 'mutation' },
  { domain: 'remote', name: 'funnelStatus', kind: 'query' },
  { domain: 'remote', name: 'setFunnelBind', kind: 'mutation' },
  { domain: 'projects', name: 'openRepoPath', kind: 'mutation' },
  { domain: 'projects', name: 'recentRepos', kind: 'query' },
  { domain: 'projects', name: 'removeRecentRepo', kind: 'mutation' },
  { domain: 'projects', name: 'browseDirs', kind: 'query' },
  { domain: 'files', name: 'readDir', kind: 'query' },
  { domain: 'files', name: 'hidePath', kind: 'mutation' },
  { domain: 'files', name: 'unhidePath', kind: 'mutation' },
  { domain: 'files', name: 'pinPath', kind: 'mutation' },
  { domain: 'files', name: 'unpinPath', kind: 'mutation' },
  { domain: 'files', name: 'pinnedEntries', kind: 'query' },
  { domain: 'files', name: 'readFile', kind: 'query' },
  { domain: 'files', name: 'previewHtml', kind: 'query' },
  { domain: 'files', name: 'writeTextFile', kind: 'mutation' },
  { domain: 'files', name: 'createFile', kind: 'mutation' },
  { domain: 'files', name: 'createFolder', kind: 'mutation' },
  { domain: 'files', name: 'renamePath', kind: 'mutation' },
  { domain: 'files', name: 'duplicatePath', kind: 'mutation' },
  { domain: 'files', name: 'trashPath', kind: 'mutation' },
  { domain: 'files', name: 'repoScope', kind: 'query' },
  { domain: 'search', name: 'searchText', kind: 'query' },
  { domain: 'search', name: 'searchCode', kind: 'query' },
  { domain: 'search', name: 'searchFiles', kind: 'query' },
  { domain: 'git', name: 'gitQuickCommand', kind: 'mutation' },
  { domain: 'git', name: 'gitPush', kind: 'mutation' },
  { domain: 'git', name: 'gitStageAll', kind: 'mutation' },
  { domain: 'git', name: 'gitUnstageAll', kind: 'mutation' },
  { domain: 'git', name: 'gitStageFile', kind: 'mutation' },
  { domain: 'git', name: 'gitUnstageFile', kind: 'mutation' },
  { domain: 'git', name: 'gitDiscardFile', kind: 'mutation' },
  { domain: 'git', name: 'gitCommit', kind: 'mutation' },
  { domain: 'git', name: 'gitGenerateCommitMessage', kind: 'mutation' },
  { domain: 'git', name: 'gitGenerateCommitGroups', kind: 'mutation' },
  { domain: 'git', name: 'gitCommitConventions', kind: 'query' },
  { domain: 'git', name: 'gitStatus', kind: 'query' },
  { domain: 'git', name: 'gitSuggestions', kind: 'query' },
  { domain: 'git', name: 'gitFlow', kind: 'query' },
  { domain: 'git', name: 'gitRangeFlow', kind: 'query' },
  { domain: 'git', name: 'gitRangeDiffFile', kind: 'query' },
  { domain: 'git', name: 'gitDiffFile', kind: 'query' },
  { domain: 'git', name: 'gitHead', kind: 'query' },
  { domain: 'git', name: 'gitBranches', kind: 'query' },
  { domain: 'git', name: 'gitCheckout', kind: 'mutation' },
  { domain: 'git', name: 'gitCreateBranch', kind: 'mutation' },
  { domain: 'git', name: 'gitWorktrees', kind: 'query' },
  { domain: 'git', name: 'gitAddWorktree', kind: 'mutation' },
  { domain: 'git', name: 'gitLog', kind: 'query' },
  { domain: 'git', name: 'gitCommitMessage', kind: 'query' },
  { domain: 'git', name: 'gitFileLog', kind: 'query' },
  { domain: 'git', name: 'gitCommitDiff', kind: 'query' },
  { domain: 'git', name: 'gitCommitFlow', kind: 'query' },
  { domain: 'git', name: 'diffReading', kind: 'query' },
  { domain: 'git', name: 'commitModels', kind: 'query' },
  { domain: 'review', name: 'worktreeInbox', kind: 'query' },
  { domain: 'review', name: 'markReviewed', kind: 'mutation' },
  { domain: 'review', name: 'unmarkReviewed', kind: 'mutation' },
  { domain: 'review', name: 'reviewedPaths', kind: 'query' },
  { domain: 'review', name: 'setReviewed', kind: 'mutation' },
  { domain: 'review', name: 'featureView', kind: 'query' },
  { domain: 'review', name: 'featureReading', kind: 'query' },
  { domain: 'review', name: 'clearFeatureReview', kind: 'mutation' },
  { domain: 'review', name: 'reviewIntent', kind: 'query' },
  { domain: 'review', name: 'reviewEvidenceDocs', kind: 'query' },
  { domain: 'review', name: 'reviewEvidenceAssets', kind: 'query' },
  { domain: 'review', name: 'reviewEvidenceAsset', kind: 'query' },
  { domain: 'review', name: 'reviewPublishCost', kind: 'query' },
  { domain: 'review', name: 'publishReview', kind: 'mutation' },
  { domain: 'review', name: 'archivedReviews', kind: 'query' },
  { domain: 'review', name: 'restoreArchivedReview', kind: 'mutation' },
  { domain: 'review', name: 'deleteArchivedReview', kind: 'mutation' },
  { domain: 'review', name: 'loopEvidence', kind: 'query' },
  { domain: 'review', name: 'loopEvidenceHtml', kind: 'query' },
  { domain: 'review', name: 'clearLoopEvidence', kind: 'mutation' },
  { domain: 'review', name: 'reviewComments', kind: 'query' },
  { domain: 'review', name: 'addReviewComment', kind: 'mutation' },
  { domain: 'review', name: 'editReviewComment', kind: 'mutation' },
  { domain: 'review', name: 'deleteReviewComment', kind: 'mutation' },
  { domain: 'review', name: 'clearResolvedReviewComments', kind: 'mutation' },
  { domain: 'review', name: 'resolveReviewComment', kind: 'mutation' },
  { domain: 'review', name: 'exploreFeature', kind: 'query' },
  { domain: 'review', name: 'repoLayers', kind: 'query' },
  { domain: 'review', name: 'setRepoLayers', kind: 'mutation' },
  { domain: 'board', name: 'boardCards', kind: 'query' },
  { domain: 'board', name: 'addBoardCard', kind: 'mutation' },
  { domain: 'board', name: 'updateBoardCard', kind: 'mutation' },
  { domain: 'board', name: 'moveBoardCard', kind: 'mutation' },
  { domain: 'board', name: 'deleteBoardCard', kind: 'mutation' },
  { domain: 'board', name: 'clearBoardCards', kind: 'mutation' },
  { domain: 'actions', name: 'actions', kind: 'query' },
  { domain: 'actions', name: 'trustActions', kind: 'mutation' },
  { domain: 'actions', name: 'addAction', kind: 'mutation' },
  { domain: 'actions', name: 'updateAction', kind: 'mutation' },
  { domain: 'actions', name: 'moveAction', kind: 'mutation' },
  { domain: 'actions', name: 'deleteAction', kind: 'mutation' },
  { domain: 'terminal', name: 'terminalSessions', kind: 'query' },
  { domain: 'terminal', name: 'renameTerminal', kind: 'mutation' },
  { domain: 'project-data', name: 'repoNotes', kind: 'query' },
  { domain: 'project-data', name: 'setRepoNotes', kind: 'mutation' },
  { domain: 'project-data', name: 'companionDispositions', kind: 'query' },
  { domain: 'project-data', name: 'companionGitVisibility', kind: 'query' },
  { domain: 'project-data', name: 'setCompanionGitVisibility', kind: 'mutation' },
  { domain: 'project-data', name: 'setCompanionDisposition', kind: 'mutation' },
] as const satisfies readonly InitialProcedureOwnership[]
