import type { ProcedureContract } from '../procedure-contract'
import {
  commitModelsInputSchema,
  commitModelsOutputSchema,
  diffReadingInputSchema,
  diffReadingOutputSchema,
  gitAddWorktreeInputSchema,
  gitAddWorktreeOutputSchema,
  gitBranchesInputSchema,
  gitBranchesOutputSchema,
  gitCheckoutInputSchema,
  gitCheckoutOutputSchema,
  gitCommitConventionsInputSchema,
  gitCommitConventionsOutputSchema,
  gitCommitDiffInputSchema,
  gitCommitDiffOutputSchema,
  gitCommitFlowInputSchema,
  gitCommitFlowOutputSchema,
  gitCommitInputSchema,
  gitCommitMessageInputSchema,
  gitCommitMessageOutputSchema,
  gitCommitOutputSchema,
  gitCreateBranchInputSchema,
  gitCreateBranchOutputSchema,
  gitDiffFileInputSchema,
  gitDiffFileOutputSchema,
  gitDiscardFileInputSchema,
  gitDiscardFileOutputSchema,
  gitFileLogInputSchema,
  gitFileLogOutputSchema,
  gitFlowInputSchema,
  gitFlowOutputSchema,
  gitGenerateCommitGroupsInputSchema,
  gitGenerateCommitGroupsOutputSchema,
  gitGenerateCommitMessageInputSchema,
  gitGenerateCommitMessageOutputSchema,
  gitHeadInputSchema,
  gitHeadOutputSchema,
  gitLogInputSchema,
  gitLogOutputSchema,
  gitPushInputSchema,
  gitPushOutputSchema,
  gitQuickCommandInputSchema,
  gitQuickCommandOutputSchema,
  gitRangeDiffFileInputSchema,
  gitRangeDiffFileOutputSchema,
  gitRangeFlowInputSchema,
  gitRangeFlowOutputSchema,
  gitStageAllInputSchema,
  gitStageAllOutputSchema,
  gitStageFileInputSchema,
  gitStageFileOutputSchema,
  gitStatusInputSchema,
  gitStatusOutputSchema,
  gitSuggestionsInputSchema,
  gitSuggestionsOutputSchema,
  gitUnstageAllInputSchema,
  gitUnstageAllOutputSchema,
  gitUnstageFileInputSchema,
  gitUnstageFileOutputSchema,
  gitWorktreesInputSchema,
  gitWorktreesOutputSchema,
} from './git.contract'

const gitProcedureDefinitions = {
  gitQuickCommand: {
    kind: 'mutation',
    input: gitQuickCommandInputSchema,
    output: gitQuickCommandOutputSchema,
    errors: [],
  },
  gitPush: { kind: 'mutation', input: gitPushInputSchema, output: gitPushOutputSchema, errors: [] },
  gitStageAll: {
    kind: 'mutation',
    input: gitStageAllInputSchema,
    output: gitStageAllOutputSchema,
    errors: [],
  },
  gitUnstageAll: {
    kind: 'mutation',
    input: gitUnstageAllInputSchema,
    output: gitUnstageAllOutputSchema,
    errors: [],
  },
  gitStageFile: {
    kind: 'mutation',
    input: gitStageFileInputSchema,
    output: gitStageFileOutputSchema,
    errors: [],
  },
  gitUnstageFile: {
    kind: 'mutation',
    input: gitUnstageFileInputSchema,
    output: gitUnstageFileOutputSchema,
    errors: [],
  },
  gitDiscardFile: {
    kind: 'mutation',
    input: gitDiscardFileInputSchema,
    output: gitDiscardFileOutputSchema,
    errors: [],
  },
  gitCommit: {
    kind: 'mutation',
    input: gitCommitInputSchema,
    output: gitCommitOutputSchema,
    errors: [],
  },
  gitGenerateCommitMessage: {
    kind: 'mutation',
    input: gitGenerateCommitMessageInputSchema,
    output: gitGenerateCommitMessageOutputSchema,
    errors: [],
  },
  gitGenerateCommitGroups: {
    kind: 'mutation',
    input: gitGenerateCommitGroupsInputSchema,
    output: gitGenerateCommitGroupsOutputSchema,
    errors: [],
  },
  gitCheckout: {
    kind: 'mutation',
    input: gitCheckoutInputSchema,
    output: gitCheckoutOutputSchema,
    errors: ['git.not-a-repository', 'git.branch-not-found', 'git.working-tree-conflict'],
  },
  gitCreateBranch: {
    kind: 'mutation',
    input: gitCreateBranchInputSchema,
    output: gitCreateBranchOutputSchema,
    errors: [],
  },
  gitAddWorktree: {
    kind: 'mutation',
    input: gitAddWorktreeInputSchema,
    output: gitAddWorktreeOutputSchema,
    errors: ['git.not-a-repository', 'git.branch-already-exists', 'git.worktree-conflict'],
  },
  gitCommitConventions: {
    kind: 'query',
    input: gitCommitConventionsInputSchema,
    output: gitCommitConventionsOutputSchema,
    errors: [],
  },
  gitStatus: {
    kind: 'query',
    input: gitStatusInputSchema,
    output: gitStatusOutputSchema,
    errors: ['git.not-a-repository'],
  },
  gitSuggestions: {
    kind: 'query',
    input: gitSuggestionsInputSchema,
    output: gitSuggestionsOutputSchema,
    errors: [],
  },
  gitFlow: { kind: 'query', input: gitFlowInputSchema, output: gitFlowOutputSchema, errors: [] },
  gitRangeFlow: {
    kind: 'query',
    input: gitRangeFlowInputSchema,
    output: gitRangeFlowOutputSchema,
    errors: [],
  },
  gitRangeDiffFile: {
    kind: 'query',
    input: gitRangeDiffFileInputSchema,
    output: gitRangeDiffFileOutputSchema,
    errors: [],
  },
  gitDiffFile: {
    kind: 'query',
    input: gitDiffFileInputSchema,
    output: gitDiffFileOutputSchema,
    errors: [],
  },
  gitHead: { kind: 'query', input: gitHeadInputSchema, output: gitHeadOutputSchema, errors: [] },
  gitBranches: {
    kind: 'query',
    input: gitBranchesInputSchema,
    output: gitBranchesOutputSchema,
    errors: ['git.not-a-repository'],
  },
  gitWorktrees: {
    kind: 'query',
    input: gitWorktreesInputSchema,
    output: gitWorktreesOutputSchema,
    errors: ['git.not-a-repository'],
  },
  gitLog: { kind: 'query', input: gitLogInputSchema, output: gitLogOutputSchema, errors: [] },
  gitCommitMessage: {
    kind: 'query',
    input: gitCommitMessageInputSchema,
    output: gitCommitMessageOutputSchema,
    errors: [],
  },
  gitFileLog: {
    kind: 'query',
    input: gitFileLogInputSchema,
    output: gitFileLogOutputSchema,
    errors: [],
  },
  gitCommitDiff: {
    kind: 'query',
    input: gitCommitDiffInputSchema,
    output: gitCommitDiffOutputSchema,
    errors: [],
  },
  gitCommitFlow: {
    kind: 'query',
    input: gitCommitFlowInputSchema,
    output: gitCommitFlowOutputSchema,
    errors: [],
  },
  diffReading: {
    kind: 'query',
    input: diffReadingInputSchema,
    output: diffReadingOutputSchema,
    errors: [],
  },
  commitModels: {
    kind: 'query',
    input: commitModelsInputSchema,
    output: commitModelsOutputSchema,
    errors: [],
  },
} as const

export type GitProcedureName = keyof typeof gitProcedureDefinitions

export const gitProcedures = gitProcedureDefinitions satisfies Record<
  GitProcedureName,
  ProcedureContract
>
