import type { ProcedureContract } from '../procedure-contract'
import type { ProcedureName } from '../procedures/names'
import {
  commitModelsInputSchema,
  commitModelsOutputSchema,
  diffReadingInputSchema,
  diffReadingOutputSchema,
  gitAddWorktreeInputSchema,
  gitAddWorktreeOutputSchema,
  gitBranchesInputSchema,
  gitBranchesOutputSchema,
  gitCheckoutInputSchema,
  gitCheckoutOutputSchema,
  gitCommitConventionsInputSchema,
  gitCommitConventionsOutputSchema,
  gitCommitDiffInputSchema,
  gitCommitDiffOutputSchema,
  gitCommitFlowInputSchema,
  gitCommitFlowOutputSchema,
  gitCommitInputSchema,
  gitCommitMessageInputSchema,
  gitCommitMessageOutputSchema,
  gitCommitOutputSchema,
  gitCreateBranchInputSchema,
  gitCreateBranchOutputSchema,
  gitDiffFileInputSchema,
  gitDiffFileOutputSchema,
  gitDiscardFileInputSchema,
  gitDiscardFileOutputSchema,
  gitFileLogInputSchema,
  gitFileLogOutputSchema,
  gitFlowInputSchema,
  gitFlowOutputSchema,
  gitGenerateCommitGroupsInputSchema,
  gitGenerateCommitGroupsOutputSchema,
  gitGenerateCommitMessageInputSchema,
  gitGenerateCommitMessageOutputSchema,
  gitHeadInputSchema,
  gitHeadOutputSchema,
  gitLogInputSchema,
  gitLogOutputSchema,
  gitPushInputSchema,
  gitPushOutputSchema,
  gitQuickCommandInputSchema,
  gitQuickCommandOutputSchema,
  gitRangeDiffFileInputSchema,
  gitRangeDiffFileOutputSchema,
  gitRangeFlowInputSchema,
  gitRangeFlowOutputSchema,
  gitStageAllInputSchema,
  gitStageAllOutputSchema,
  gitStageFileInputSchema,
  gitStageFileOutputSchema,
  gitStatusInputSchema,
  gitStatusOutputSchema,
  gitSuggestionsInputSchema,
  gitSuggestionsOutputSchema,
  gitUnstageAllInputSchema,
  gitUnstageAllOutputSchema,
  gitUnstageFileInputSchema,
  gitUnstageFileOutputSchema,
  gitWorktreesInputSchema,
  gitWorktreesOutputSchema,
} from './git.contract'

const gitProcedureDefinitions = {
  gitQuickCommand: {
    kind: 'mutation',
    input: gitQuickCommandInputSchema,
    output: gitQuickCommandOutputSchema,
  },
  gitPush: { kind: 'mutation', input: gitPushInputSchema, output: gitPushOutputSchema },
  gitStageAll: {
    kind: 'mutation',
    input: gitStageAllInputSchema,
    output: gitStageAllOutputSchema,
  },
  gitUnstageAll: {
    kind: 'mutation',
    input: gitUnstageAllInputSchema,
    output: gitUnstageAllOutputSchema,
  },
  gitStageFile: {
    kind: 'mutation',
    input: gitStageFileInputSchema,
    output: gitStageFileOutputSchema,
  },
  gitUnstageFile: {
    kind: 'mutation',
    input: gitUnstageFileInputSchema,
    output: gitUnstageFileOutputSchema,
  },
  gitDiscardFile: {
    kind: 'mutation',
    input: gitDiscardFileInputSchema,
    output: gitDiscardFileOutputSchema,
  },
  gitCommit: { kind: 'mutation', input: gitCommitInputSchema, output: gitCommitOutputSchema },
  gitGenerateCommitMessage: {
    kind: 'mutation',
    input: gitGenerateCommitMessageInputSchema,
    output: gitGenerateCommitMessageOutputSchema,
  },
  gitGenerateCommitGroups: {
    kind: 'mutation',
    input: gitGenerateCommitGroupsInputSchema,
    output: gitGenerateCommitGroupsOutputSchema,
  },
  gitCheckout: {
    kind: 'mutation',
    input: gitCheckoutInputSchema,
    output: gitCheckoutOutputSchema,
  },
  gitCreateBranch: {
    kind: 'mutation',
    input: gitCreateBranchInputSchema,
    output: gitCreateBranchOutputSchema,
  },
  gitAddWorktree: {
    kind: 'mutation',
    input: gitAddWorktreeInputSchema,
    output: gitAddWorktreeOutputSchema,
  },
  gitCommitConventions: {
    kind: 'query',
    input: gitCommitConventionsInputSchema,
    output: gitCommitConventionsOutputSchema,
  },
  gitStatus: { kind: 'query', input: gitStatusInputSchema, output: gitStatusOutputSchema },
  gitSuggestions: {
    kind: 'query',
    input: gitSuggestionsInputSchema,
    output: gitSuggestionsOutputSchema,
  },
  gitFlow: { kind: 'query', input: gitFlowInputSchema, output: gitFlowOutputSchema },
  gitRangeFlow: {
    kind: 'query',
    input: gitRangeFlowInputSchema,
    output: gitRangeFlowOutputSchema,
  },
  gitRangeDiffFile: {
    kind: 'query',
    input: gitRangeDiffFileInputSchema,
    output: gitRangeDiffFileOutputSchema,
  },
  gitDiffFile: {
    kind: 'query',
    input: gitDiffFileInputSchema,
    output: gitDiffFileOutputSchema,
  },
  gitHead: { kind: 'query', input: gitHeadInputSchema, output: gitHeadOutputSchema },
  gitBranches: { kind: 'query', input: gitBranchesInputSchema, output: gitBranchesOutputSchema },
  gitWorktrees: {
    kind: 'query',
    input: gitWorktreesInputSchema,
    output: gitWorktreesOutputSchema,
  },
  gitLog: { kind: 'query', input: gitLogInputSchema, output: gitLogOutputSchema },
  gitCommitMessage: {
    kind: 'query',
    input: gitCommitMessageInputSchema,
    output: gitCommitMessageOutputSchema,
  },
  gitFileLog: { kind: 'query', input: gitFileLogInputSchema, output: gitFileLogOutputSchema },
  gitCommitDiff: {
    kind: 'query',
    input: gitCommitDiffInputSchema,
    output: gitCommitDiffOutputSchema,
  },
  gitCommitFlow: {
    kind: 'query',
    input: gitCommitFlowInputSchema,
    output: gitCommitFlowOutputSchema,
  },
  diffReading: {
    kind: 'query',
    input: diffReadingInputSchema,
    output: diffReadingOutputSchema,
  },
  commitModels: {
    kind: 'query',
    input: commitModelsInputSchema,
    output: commitModelsOutputSchema,
  },
} as const

export type GitProcedureName = Extract<keyof typeof gitProcedureDefinitions, ProcedureName>

export const gitProcedures = gitProcedureDefinitions satisfies Record<
  GitProcedureName,
  ProcedureContract
>
