import type { ProcedureContract } from '../procedure-contract'
import type { ProcedureName } from '../procedures/names'
import {
  addReviewCommentInputSchema,
  archivedReviewsOutputSchema,
  clearResolvedReviewCommentsInputSchema,
  deleteArchivedReviewInputSchema,
  deleteReviewCommentInputSchema,
  editReviewCommentInputSchema,
  evidenceAssetBodySchema,
  evidenceMetaSchema,
  evidenceSchema,
  exploreFeatureInputSchema,
  featureReadingOutputSchema,
  featureReadingSchema,
  featureViewSchema,
  markReviewedInputSchema,
  publishCostSchema,
  publishResultSchema,
  repoLayersOutputSchema,
  resolveReviewCommentInputSchema,
  restoreArchivedReviewInputSchema,
  reviewCommentSchema,
  reviewEvidenceAssetInputSchema,
  reviewEvidenceAssetsOutputSchema,
  reviewEvidenceDocsOutputSchema,
  reviewedPathsInputSchema,
  reviewedPathsOutputSchema,
  reviewIntentOutputSchema,
  reviewRepoPathInputSchema,
  setRepoLayersInputSchema,
  setReviewedInputSchema,
  unmarkReviewedInputSchema,
  voidOutputSchema,
  worktreeInboxInputSchema,
  worktreeInboxOutputSchema,
} from './review.contract'

const reviewProcedureDefinitions = {
  worktreeInbox: {
    kind: 'query',
    input: worktreeInboxInputSchema,
    output: worktreeInboxOutputSchema,
    errors: [],
  },
  markReviewed: {
    kind: 'mutation',
    input: markReviewedInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  unmarkReviewed: {
    kind: 'mutation',
    input: unmarkReviewedInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  reviewedPaths: {
    kind: 'query',
    input: reviewedPathsInputSchema,
    output: reviewedPathsOutputSchema,
    errors: [],
  },
  setReviewed: {
    kind: 'mutation',
    input: setReviewedInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  featureView: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: featureViewSchema,
    errors: [],
  },
  featureReading: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: featureReadingOutputSchema,
    errors: [],
  },
  clearFeatureReview: {
    kind: 'mutation',
    input: reviewRepoPathInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  reviewIntent: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: reviewIntentOutputSchema,
    errors: [],
  },
  reviewEvidenceDocs: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: reviewEvidenceDocsOutputSchema,
    errors: [],
  },
  reviewEvidenceAssets: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: reviewEvidenceAssetsOutputSchema,
    errors: [],
  },
  reviewEvidenceAsset: {
    kind: 'query',
    input: reviewEvidenceAssetInputSchema,
    output: evidenceAssetBodySchema.nullable(),
    errors: [],
  },
  reviewPublishCost: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: publishCostSchema,
    errors: [],
  },
  publishReview: {
    kind: 'mutation',
    input: reviewRepoPathInputSchema,
    output: publishResultSchema.nullable(),
    errors: [],
  },
  archivedReviews: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: archivedReviewsOutputSchema,
    errors: [],
  },
  restoreArchivedReview: {
    kind: 'mutation',
    input: restoreArchivedReviewInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  deleteArchivedReview: {
    kind: 'mutation',
    input: deleteArchivedReviewInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  loopEvidence: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: evidenceMetaSchema.nullable(),
    errors: [],
  },
  loopEvidenceHtml: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: evidenceSchema.nullable(),
    errors: [],
  },
  clearLoopEvidence: {
    kind: 'mutation',
    input: reviewRepoPathInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  reviewComments: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: reviewCommentSchema.array(),
    errors: [],
  },
  addReviewComment: {
    kind: 'mutation',
    input: addReviewCommentInputSchema,
    output: reviewCommentSchema,
    errors: [],
  },
  editReviewComment: {
    kind: 'mutation',
    input: editReviewCommentInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  deleteReviewComment: {
    kind: 'mutation',
    input: deleteReviewCommentInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  clearResolvedReviewComments: {
    kind: 'mutation',
    input: clearResolvedReviewCommentsInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  resolveReviewComment: {
    kind: 'mutation',
    input: resolveReviewCommentInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
  exploreFeature: {
    kind: 'query',
    input: exploreFeatureInputSchema,
    output: featureReadingSchema,
    errors: [],
  },
  repoLayers: {
    kind: 'query',
    input: reviewRepoPathInputSchema,
    output: repoLayersOutputSchema,
    errors: [],
  },
  setRepoLayers: {
    kind: 'mutation',
    input: setRepoLayersInputSchema,
    output: voidOutputSchema,
    errors: [],
  },
} as const

export type ReviewProcedureName = Extract<keyof typeof reviewProcedureDefinitions, ProcedureName>

export const reviewProcedures = reviewProcedureDefinitions satisfies Record<
  ReviewProcedureName,
  ProcedureContract
>
