import {
  DEVICE_LABEL_LENGTH,
  ENVIRONMENT_NAME_LENGTH,
} from '@porcelain/contracts/shared';
export const WEB_PLATFORM_NAME_MAX_LENGTH = 120;
export const PAIRING_PENDING_MS = 0;
export const PROJECT_DISCOVERY_STALE_MS = 60_000;
export const HISTORY_OID_LENGTH = 7;
export const HISTORY_ROW_HEIGHT = 58;
export const HISTORY_LANE_WIDTH = 16;
export const HISTORY_GRAPH_INSET = 13;
export const HISTORY_GRAPH_ROW_GAP = 8;
export const HISTORY_GRAPH_MERGE_RADIUS = 5;
export const HISTORY_GRAPH_DOT_RADIUS = 4;
export const HISTORY_GRAPH_STROKE_WIDTH = 1.5;
export const HISTORY_GRAPH_DOT_STROKE_WIDTH = 2;
export const HISTORY_LOAD_AHEAD_PX = 240;
export const HISTORY_ORDINAL_CENTURY = 100;
export const HISTORY_ORDINAL_TEENS_START = 11;
export const HISTORY_ORDINAL_TEENS_END = 13;
export const HISTORY_ORDINAL_DECADE = 10;
export const FILE_AUTOSAVE_WAIT_MS = 3_000;
export const FILE_DISK_CHANGE_NOTICE_MS = 8_000;
export const FILE_QUICK_OPEN_MAX = 50;
export const FILE_PREVIEW_MAX_ASSETS = 64;
export const FILE_PREVIEW_MAX_BYTES = 28 * 1024 * 1024;
export const FILE_PREVIEW_MAX_ROUNDS = 8;
export const FILE_ICON_DEFAULT_SIZE = 16;
export const FILE_NAME_SUFFIX_START = 2;
export const GIT_ACTION_REJECTED_STATUSES = [409, 503];
export const REVIEW_PATCH_CONTEXT_LINES = 3;

export const COMMIT_MODELS_STALE_MS = 60_000;
export const DISCARD_RESTORE_TOAST_MS = 10_000;
export const PUBLISHED_REVIEW_REFRESH_MS = 1_800_000;
export const REVIEW_DIAGRAM_FIT_WAIT_MS = 120;
export const PIERRE_WORKER_POOL_SIZE = 4;
export const WORKSPACE_SEARCH_VALUE_MAX_LENGTH = 8192;
export const PAIRING_LABEL_MAX_LENGTH = DEVICE_LABEL_LENGTH;
export const ENVIRONMENT_NAME_MAX_LENGTH = ENVIRONMENT_NAME_LENGTH;
export const REMOTE_ACCESS_SETTLING_POLL_MS = 1_000;
export const SERVICE_UPDATE_POLL_MS = 1_000;
export const PAIRING_QR_BORDER_MODULES = 2;
export const FILE_FIND_MAX_MATCHES = 10_000;
export const DIFF_WINDOW_FILES = 25;
