const MEBIBYTE = 1024 * 1024;
const JSON_ESCAPE_FACTOR = 6;
const ENVELOPE_BYTES = MEBIBYTE;

const REVIEW_SUMMARY_BYTES = 10 * MEBIBYTE;
export const REVIEW_BODY_LIMIT =
  JSON_ESCAPE_FACTOR * REVIEW_SUMMARY_BYTES + ENVELOPE_BYTES;
export const EDIT_FILE_BODY_LIMIT = 8 * MEBIBYTE;
