const KIBIBYTE = 1024;
const MEBIBYTE = 1024 * KIBIBYTE;

export const TEXT_BYTES = MEBIBYTE;
export const REVIEW_SUMMARY_MEBIBYTES = 10;
export const REVIEW_SUMMARY_BYTES = REVIEW_SUMMARY_MEBIBYTES * MEBIBYTE;
export const COMMIT_MESSAGE_BYTES = 16 * KIBIBYTE;
export const COMMIT_GROUPS = 20;
export const CHANGED_PATHS = 2000;
export const REVIEWED_FILE_MARKS = 2000;
export const DIRECTORY_ENTRIES = 2000;
export const PATH_LENGTH = 4096;
export const DEVICE_LABEL_LENGTH = 80;
export const DEVICE_PLATFORM_LENGTH = 120;
export const WORKTREE_ID_LENGTH = 32;
