// Where an area is today and where we decided to take it, as plain-language
// swimlane diagrams. Updated as decisions are made in the review sessions;
// the Notion page linked from each plan is the written record.
import type { AreaId } from './types';

export type DesignNode = {
  id: string;
  /** Column index into the diagram's lanes. */
  lane: number;
  label: string;
  detail?: string;
  kind: 'actor' | 'credential' | 'component' | 'storage' | 'transport';
  /** How this box compares with today (planned diagrams only). */
  change?: 'new' | 'changed' | 'removed';
  /** A known problem with today's design (current diagrams only). */
  problem?: string;
};

export type DesignEdge = {
  from: string;
  to: string;
  label?: string;
  dashed?: boolean;
};

export type Diagram = {
  lanes: string[];
  nodes: DesignNode[];
  edges: DesignEdge[];
};

export type AreaPlan = {
  area: AreaId;
  title: string;
  notion?: string;
  current: Diagram;
  planned: Diagram;
  /** What changes, in one line each. */
  changes: string[];
  decidedOn?: string;
  /** When the review of this area in the lab was finished. */
  reviewedOn?: string;
};

export const plans: AreaPlan[] = [
  {
    area: 'connection',
    title: 'Device pairing instead of one shared token',
    notion: 'https://app.notion.com/p/3df4ccb1d6b88184a465dc261ac43bed',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Each device pairs once with a link (15 min, single use) and gets its own token.',
      'Tokens are bearer tokens, stored hashed; a device is revoked on its own; 90 days unused expires it.',
      'Only the owner pairs and revokes, through a local socket on the server machine, never over the network.',
      'Agents connect with `porcelain mcp` through the same socket: no secrets in agent configs, always the author "agent".',
      'The admin token and the token-derived browser cookie go away (done, 2026-09-20).',
      'No LAN encryption of our own: home Wi-Fi is trusted, Tailscale and Cloudflare already encrypt.',
      'The server serves the web app on its own origin: the web shows that one server; desktop and mobile combine several.',
      'API routes are registered once, under /api (to-do).',
    ],
    current: {
      lanes: [
        'Who connects',
        'What they present',
        'Porcelain server',
        'On the server machine',
      ],
      nodes: [
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Web browser',
          detail: 'Opens a pairing link once, then holds a cookie',
        },
        {
          id: 'cli',
          lane: 0,
          kind: 'actor',
          label: 'You, in a terminal',
          detail: 'porcelain pair · devices · revoke',
        },
        {
          id: 'agents',
          lane: 0,
          kind: 'actor',
          label: 'Agents (Claude Code, Codex)',
          detail: 'porcelain mcp, over the socket',
        },
        {
          id: 'link',
          lane: 1,
          kind: 'credential',
          label: 'Pairing link',
          detail: '15 minutes, single use; the code rides in the URL fragment',
        },
        {
          id: 'device',
          lane: 1,
          kind: 'credential',
          label: 'Device credential',
          detail:
            'Stored hashed; a browser holds it as an HttpOnly cookie, anything else as a bearer',
        },
        {
          id: 'pairing',
          lane: 2,
          kind: 'component',
          label: 'Pairing',
          detail:
            'One immediate transaction: consume the grant, create the device',
        },
        {
          id: 'auth',
          lane: 2,
          kind: 'component',
          label: 'authenticate()',
          detail:
            'Credential → the device it belongs to, from an in-memory digest map',
          problem:
            'Every caller is a viewer: there is still no reviewer-versus-guest distinction to make.',
        },
        {
          id: 'routes',
          lane: 2,
          kind: 'component',
          label: 'API routes, once under /api',
          detail: 'Also serves the web app; no MCP route on the network',
        },
        {
          id: 'socket',
          lane: 3,
          kind: 'storage',
          label: 'Owner socket in the data directory (0600)',
          detail:
            'File permissions are the authentication; unreachable from the network',
        },
        {
          id: 'devices',
          lane: 3,
          kind: 'storage',
          label: 'Grants and devices tables',
          detail: 'Hashed secrets, label, last seen, revoked',
        },
      ],
      edges: [
        { from: 'cli', to: 'socket', label: 'pair / revoke' },
        { from: 'agents', to: 'socket', label: 'MCP' },
        { from: 'socket', to: 'pairing', label: 'issue link' },
        { from: 'pairing', to: 'link' },
        { from: 'link', to: 'web', label: 'opened once', dashed: true },
        { from: 'web', to: 'device', label: 'redeem → cookie' },
        { from: 'device', to: 'auth' },
        { from: 'auth', to: 'routes' },
        { from: 'auth', to: 'devices', label: 'digest map', dashed: true },
        { from: 'pairing', to: 'devices', label: 'writes' },
      ],
    },
    planned: {
      lanes: [
        'Who connects',
        'How they connect',
        'Porcelain server',
        'On the server machine',
      ],
      nodes: [
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Web browser',
          detail: 'Served by this server; shows this one server',
        },
        {
          id: 'electron',
          lane: 0,
          kind: 'actor',
          label: 'Electron app',
          detail: 'Several servers, one token each',
          change: 'new',
        },
        {
          id: 'phone',
          lane: 0,
          kind: 'actor',
          label: 'iPhone / iPad (Expo)',
          detail: 'Several servers, one token each',
          change: 'new',
        },
        {
          id: 'link',
          lane: 1,
          kind: 'credential',
          label: 'Pairing link',
          detail: '15 minutes, single use, long random code, link or QR',
          change: 'new',
        },
        {
          id: 'device-token',
          lane: 1,
          kind: 'credential',
          label: 'Device token',
          detail:
            'Bearer; kept in the keychain or an HttpOnly cookie; until revoked or 90 days unused',
          change: 'new',
        },
        {
          id: 'network',
          lane: 1,
          kind: 'transport',
          label: 'Home Wi-Fi · Tailscale · Cloudflare',
          detail: 'Plain HTTP at home; encrypted away from home',
        },
        {
          id: 'pairing',
          lane: 2,
          kind: 'component',
          label: 'Pairing',
          detail: 'Consumes the link once, creates the device',
          change: 'new',
        },
        {
          id: 'auth',
          lane: 2,
          kind: 'component',
          label: 'Who is calling?',
          detail: 'Token → device (viewer); socket → agent or owner',
          change: 'changed',
        },
        {
          id: 'routes',
          lane: 2,
          kind: 'component',
          label: 'API under /api, and MCP',
          detail:
            'Know the caller: reviewer, agent or owner. Registered once; also serves the web app',
          change: 'changed',
        },
        {
          id: 'owner',
          lane: 3,
          kind: 'actor',
          label: 'You (or Claude) in a terminal, or Electron',
          detail: 'porcelain pair · revoke · devices',
        },
        {
          id: 'agents',
          lane: 3,
          kind: 'actor',
          label: 'Agents: porcelain mcp',
          detail: 'No secrets in any agent config',
          change: 'changed',
        },
        {
          id: 'socket',
          lane: 3,
          kind: 'storage',
          label: 'Local socket ~/.porcelain (0600)',
          detail:
            'File permissions are the authentication; not reachable from the network',
          change: 'new',
        },
        {
          id: 'devices',
          lane: 3,
          kind: 'storage',
          label: 'Devices table',
          detail: 'Hashed tokens, label, last seen, revoked',
          change: 'new',
        },
      ],
      edges: [
        { from: 'owner', to: 'socket', label: 'pair / revoke' },
        { from: 'agents', to: 'socket', label: 'MCP' },
        { from: 'socket', to: 'pairing', label: 'issue link' },
        { from: 'pairing', to: 'link', label: 'shown as link or QR' },
        { from: 'link', to: 'web', label: 'paste once', dashed: true },
        { from: 'link', to: 'electron', dashed: true },
        { from: 'link', to: 'phone', label: 'scan once', dashed: true },
        { from: 'phone', to: 'device-token', label: 'redeem → token' },
        { from: 'web', to: 'device-token' },
        { from: 'electron', to: 'device-token' },
        { from: 'device-token', to: 'network', label: 'every request' },
        { from: 'network', to: 'auth' },
        { from: 'socket', to: 'auth', label: 'agent / owner' },
        { from: 'auth', to: 'routes' },
        { from: 'pairing', to: 'devices', label: 'store hash' },
        {
          from: 'auth',
          to: 'devices',
          label: 'look up (cached)',
          dashed: true,
        },
      ],
    },
  },
  {
    area: 'inventory',
    title: 'Worktrees live from Git',
    notion: 'https://app.notion.com/p/3df4ccb1d6b8812aa9e1e80951b8efcb',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Projects stay in the database; worktrees are listed live from Git (one process per project) (done, 2026-09-20).',
      'No worktree table, no refresh route, no reconciliation; a focus lists rather than rescans (done, 2026-09-20).',
      'Worktree IDs are derived from the filesystem identity of the worktree’s Git directory: stable across moves, new when recreated (done, 2026-09-20).',
      'Review data rows appear with the first comment, mark, layer or artifact (done, 2026-09-20).',
      'Review data of worktrees Git no longer reports is deleted after 30 days (done, 2026-09-20).',
      'IDs resolve to paths from an in-memory map, not a SQLite read per request (done, 2026-09-20).',
      'No file-count badge: a status dot (green = review ready, yellow = the agent replied), returned with the list from SQLite.',
      'Projects are listed in parallel, a few at a time, each with its own timeout: one hanging project no longer fails the rest.',
      'Project names come from the origin remote URL (else the main folder); the owner can rename.',
      'Removing a project is always allowed; it never touches the disk.',
    ],
    current: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Database',
        'Git and the filesystem',
      ],
      nodes: [
        {
          id: 'focus',
          lane: 0,
          kind: 'actor',
          label: 'Mount, reconnect, every window focus',
          detail:
            'Reading the inventory is the listing; there is nothing else to ask',
          problem:
            'Still one Git process per project on every alt-tab, and projects are listed one after another under a single deadline.',
        },
        {
          id: 'sidebar',
          lane: 0,
          kind: 'actor',
          label: 'Sidebar and every worktree request',
        },
        {
          id: 'badges',
          lane: 0,
          kind: 'actor',
          label: 'Badge: files to review, per worktree',
          problem:
            'One request per worktree, one at a time: 13 Git processes each, or a full diff of every file once any file was marked.',
        },
        {
          id: 'list',
          lane: 1,
          kind: 'component',
          label: 'List worktrees',
          detail: 'One git worktree list per project, on the inventory lane',
        },
        {
          id: 'identity',
          lane: 1,
          kind: 'component',
          label: 'Derived worktree ID',
          detail:
            'Hash of the project and the administrative Git directory’s device, inode and birth time',
        },
        {
          id: 'map',
          lane: 1,
          kind: 'component',
          label: 'In-memory ID → path',
          detail:
            'Rebuilt by each listing; a worktree Git has stopped reporting is still reachable as its last-known self',
        },
        {
          id: 'cleanup',
          lane: 1,
          kind: 'component',
          label: 'Cleanup',
          detail:
            'Hourly; only a listing that succeeded starts a worktree’s thirty-day clock',
        },
        {
          id: 'summary',
          lane: 1,
          kind: 'component',
          label: 'Review summary',
          detail:
            'Status read, or full evidence read when marks exist; own queue',
        },
        {
          id: 'tables',
          lane: 2,
          kind: 'storage',
          label: 'projects · worktree_presence',
          detail:
            'What the owner registered, and how long each worktree has been gone',
        },
        {
          id: 'review',
          lane: 2,
          kind: 'storage',
          label: 'Review data',
          detail:
            'Comments, marks, layers, artifacts by derived worktree ID; rows appear with the first one',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git worktree list',
          detail: 'One process per project; none per worktree',
        },
        {
          id: 'stat',
          lane: 3,
          kind: 'storage',
          label: 'Stat of each worktree’s Git directory',
          detail: 'No Git process',
        },
      ],
      edges: [
        { from: 'focus', to: 'list', label: 'always' },
        { from: 'list', to: 'tables', label: 'which repositories' },
        { from: 'list', to: 'git' },
        { from: 'list', to: 'identity' },
        { from: 'identity', to: 'stat' },
        { from: 'identity', to: 'map' },
        { from: 'sidebar', to: 'map', label: 'ID → path' },
        {
          from: 'list',
          to: 'cleanup',
          label: 'what still exists',
          dashed: true,
        },
        { from: 'cleanup', to: 'review', dashed: true },
        { from: 'badges', to: 'summary', label: 'per worktree' },
        { from: 'summary', to: 'git', label: 'status or every diff' },
      ],
    },
    planned: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Database',
        'Git and the filesystem',
      ],
      nodes: [
        {
          id: 'sidebar',
          lane: 0,
          kind: 'actor',
          label: 'Sidebar',
          detail:
            'Asks for the list when it needs it; status dot: green = review ready, yellow = agent replied; no counts',
          change: 'changed',
        },
        { id: 'requests', lane: 0, kind: 'actor', label: 'Worktree requests' },
        {
          id: 'list',
          lane: 1,
          kind: 'component',
          label: 'List worktrees',
          detail:
            'Projects in parallel, each with its own timeout; concurrent listings of one repository share a single read',
          change: 'changed',
        },
        {
          id: 'identity',
          lane: 1,
          kind: 'component',
          label: 'Derived worktree ID',
          detail:
            'Hash of project + Git directory identity (device, inode, birth time)',
        },
        {
          id: 'map',
          lane: 1,
          kind: 'component',
          label: 'In-memory ID → path',
          detail: 'Last listing per project; no SQLite read per request',
        },
        {
          id: 'ready',
          lane: 1,
          kind: 'component',
          label: 'Worktree status',
          detail:
            'Review ready (live layers) · agent replied (unseen reply); one SQLite query for all, sent with the list',
          change: 'new',
        },
        {
          id: 'cleanup',
          lane: 1,
          kind: 'component',
          label: 'Cleanup',
          detail: 'Review data of worktrees gone for 30 days is deleted',
        },
        {
          id: 'projects',
          lane: 2,
          kind: 'storage',
          label: 'projects · worktree_presence',
          detail:
            'What the owner registered, and how long each worktree has been gone',
        },
        {
          id: 'review',
          lane: 2,
          kind: 'storage',
          label: 'Review data',
          detail:
            'By derived worktree ID; created with the first comment or mark',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git worktree list',
          detail: 'One process per project',
        },
        {
          id: 'stat',
          lane: 3,
          kind: 'storage',
          label: 'Stat of each worktree’s Git directory',
          detail: 'No Git process',
        },
      ],
      edges: [
        { from: 'sidebar', to: 'list' },
        { from: 'list', to: 'projects', label: 'which repositories' },
        { from: 'list', to: 'git' },
        { from: 'list', to: 'identity' },
        { from: 'identity', to: 'stat' },
        { from: 'identity', to: 'map' },
        { from: 'requests', to: 'map', label: 'ID → path' },
        { from: 'list', to: 'ready' },
        { from: 'ready', to: 'review', label: 'layers published?' },
        { from: 'cleanup', to: 'review', dashed: true },
        {
          from: 'list',
          to: 'cleanup',
          label: 'what still exists',
          dashed: true,
        },
      ],
    },
  },
  {
    area: 'changes',
    title: 'Small lazy reads, no per-call guards',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881d4a845e4f1748d95d4',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Checkout identity is verified once per request, not before and after every Git call.',
      'Conversion filters are re-checked only when .gitattributes or the Git config change.',
      'Kept: reads never lock the index (GIT_OPTIONAL_LOCKS=0) and the scrubbed Git environment.',
      'The all-in-one evidence read goes away: a list of changes, one file’s diff, a line range at the last commit or on disk.',
      'Clients fetch diffs and snippets as they scroll into view; no refetch on window focus.',
      'Direction: the review becomes flows of steps with code (like this Map); plain Changes stays as the fallback.',
      'The overview needs no diffs; opening a layer or flow loads only its diffs. The handoff drops the all-diffs scroll.',
      'No cache to start with; identical in-flight reads share one answer.',
      'Tests assert Git process budgets: open a worktree ≤ 2, open a layer 1, line range 0–1, mark reviewed 0.',
      'The word “evidence” is retired: changes, diff, fingerprint.',
    ],
    current: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Guards around every Git call',
        'Git',
      ],
      nodes: [
        {
          id: 'open',
          lane: 0,
          kind: 'actor',
          label: 'Open a worktree, and every window focus',
          problem:
            'Downloads every patch and untracked file (up to 16 MB) even to look at one file.',
        },
        {
          id: 'mark',
          lane: 0,
          kind: 'actor',
          label: 'Mark reviewed (one request per file)',
          problem:
            '“Mark all” of 50 files is about 650 Git processes, one after another.',
        },
        {
          id: 'status',
          lane: 1,
          kind: 'component',
          label: 'Status',
          detail: '13 Git processes',
        },
        {
          id: 'evidence',
          lane: 1,
          kind: 'component',
          label: 'Evidence: every diff at once',
          detail:
            'Cached by status token + file stamps; files written in the last 2 s always miss',
        },
        {
          id: 'marking',
          lane: 1,
          kind: 'component',
          label: 'Set reviewed',
          detail: 'Re-reads the file’s evidence before saving the mark',
        },
        {
          id: 'identity',
          lane: 2,
          kind: 'component',
          label: 'Identity check before and after',
          detail: '4 rev-parse processes per call',
        },
        {
          id: 'filters',
          lane: 2,
          kind: 'component',
          label: 'Filter check, twice',
          problem:
            'Lists and attribute-checks every tracked file: cost grows with repository size.',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'status · diff per file · ls-files · check-attr',
        },
      ],
      edges: [
        { from: 'open', to: 'status' },
        { from: 'open', to: 'evidence' },
        { from: 'mark', to: 'marking' },
        { from: 'marking', to: 'evidence', label: 'one path' },
        { from: 'evidence', to: 'status', label: 'before and after' },
        { from: 'status', to: 'identity' },
        { from: 'status', to: 'filters' },
        { from: 'evidence', to: 'identity' },
        { from: 'identity', to: 'git' },
        { from: 'filters', to: 'git' },
      ],
    },
    planned: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Checked once',
        'Git and the disk',
      ],
      nodes: [
        {
          id: 'review',
          lane: 0,
          kind: 'actor',
          label: 'Behaviour review or plain Changes',
          detail:
            'Overview needs no diffs; opening a layer or flow loads only its diffs; plain Changes loads as it scrolls',
          change: 'changed',
        },
        {
          id: 'mark',
          lane: 0,
          kind: 'actor',
          label: 'Mark reviewed',
          detail:
            'Sends the fingerprint it showed; “mark all” is one request (section 4)',
          change: 'changed',
        },
        {
          id: 'list',
          lane: 1,
          kind: 'component',
          label: 'List of changes',
          detail:
            'Paths, kinds, cheap fingerprints; “not modified” when unchanged; identical reads in flight share one answer; no cache',
          change: 'new',
        },
        {
          id: 'diff',
          lane: 1,
          kind: 'component',
          label: 'One file’s diff',
          detail: 'Its hunks; the old POST git/diff',
          change: 'changed',
        },
        {
          id: 'range',
          lane: 1,
          kind: 'component',
          label: 'A line range of a file',
          detail: 'At the last commit or on disk, for context steps',
          change: 'new',
        },
        {
          id: 'marks',
          lane: 1,
          kind: 'storage',
          label: 'Marks in SQLite',
          detail: 'A database write, no Git read',
          change: 'changed',
        },
        {
          id: 'identity',
          lane: 2,
          kind: 'component',
          label: 'Identity once per request',
          change: 'changed',
        },
        {
          id: 'filters',
          lane: 2,
          kind: 'component',
          label: 'Filter check, cached',
          detail: 'Re-run only when .gitattributes or the Git config change',
          change: 'changed',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git status · git diff -- path · git show HEAD:path',
          detail: 'About one process per read',
        },
        {
          id: 'disk',
          lane: 3,
          kind: 'storage',
          label: 'Working-tree files',
          detail: 'Read straight from disk, no Git',
        },
      ],
      edges: [
        { from: 'review', to: 'list' },
        { from: 'review', to: 'diff', label: 'as it scrolls' },
        { from: 'review', to: 'range', label: 'context steps' },
        { from: 'mark', to: 'marks' },
        { from: 'list', to: 'identity' },
        { from: 'list', to: 'filters' },
        { from: 'list', to: 'git' },
        { from: 'diff', to: 'git' },
        { from: 'range', to: 'git', label: 'last commit' },
        { from: 'range', to: 'disk', label: 'on disk' },
      ],
    },
  },
  {
    area: 'review-layers',
    title: 'An HTML summary and layers of code',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881319f8ddbbb1dc8a15d',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'No handoff.md: the summary is one HTML page written by the agent, shown first; the code lives in the layers.',
      'A layer reads like this Map’s Code view: lanes, then steps with a label, a title, a short explanation and the code.',
      'Graphs drawn by Porcelain, like this lab: the summary has an optional Before/After diagram (lanes, boxes, New/Changed/Removed) whose boxes open layers; each layer’s graph is built from its steps.',
      'Changed steps show their block as a diff; context steps show plain code.',
      'Comments attach to code (a file or a line range), not to steps; the server already supports both.',
      'Summary HTML like T3 Code: its own link, a blank identity, scripts, CDNs and fonts allowed; one file up to 10 MB; the theme is passed in; #layer-N links open a layer.',
      'Code pointers survive edits (lines, function name, text fingerprint); a step that cannot be found says the code changed.',
      'Changed lines that no step explains are listed as “Not explained”, and publishing returns them to the agent.',
      'The whole review is replaced with a revision; only the latest is kept.',
      'Per-commit snapshots are removed (deferred); committed steps fold away and the review hides when nothing it describes is uncommitted.',
      'Marks: tick a layer (fingerprinted from its code) or, in plain Changes, a file. Dot: green when ready, hollow green when everything is reviewed but not committed.',
      'MCP: publish_review and read_review replace replace_layers and the handoff artifacts; an agent skill teaches layers and the design guide.',
      'Clients read the review once on open, then only when it changes.',
    ],
    current: {
      lanes: ['Agent (MCP)', 'Web app', 'Porcelain server', 'Storage'],
      nodes: [
        {
          id: 'replace',
          lane: 0,
          kind: 'actor',
          label: 'replace_layers',
          detail: 'Layers: a title, a markdown summary and a list of files',
        },
        {
          id: 'handoff',
          lane: 0,
          kind: 'actor',
          label: 'publish_artifact: handoff.md and handoff.html',
          problem: 'Three things published separately that can disagree.',
        },
        {
          id: 'review',
          lane: 1,
          kind: 'actor',
          label: 'Review screen',
          detail: 'Markdown handoff, report tab, layers as lists of files',
          problem: 'Re-reads the layers with every status fetch.',
        },
        { id: 'commit', lane: 1, kind: 'actor', label: 'Commit in Porcelain' },
        {
          id: 'layers',
          lane: 2,
          kind: 'component',
          label: 'Layers',
          detail:
            'Whole set replaced with a revision; a stale revision is refused',
        },
        { id: 'artifacts', lane: 2, kind: 'component', label: 'Artifacts' },
        {
          id: 'archive',
          lane: 2,
          kind: 'component',
          label: 'Archive on commit',
          detail: '11 Git processes inside the commit',
          problem: 'Matches files by path only; agent commits never archive.',
        },
        {
          id: 'associate',
          lane: 2,
          kind: 'component',
          label: 'Attach layers to a commit',
          problem: 'Nothing calls it.',
        },
        {
          id: 'live',
          lane: 3,
          kind: 'storage',
          label: 'Live layers per worktree',
        },
        {
          id: 'snapshots',
          lane: 3,
          kind: 'storage',
          label: 'Layer snapshots per commit',
          detail: 'Read by History',
        },
        { id: 'files', lane: 3, kind: 'storage', label: 'Artifact contents' },
      ],
      edges: [
        { from: 'replace', to: 'layers' },
        { from: 'handoff', to: 'artifacts' },
        { from: 'review', to: 'layers', label: 'every status fetch' },
        { from: 'review', to: 'artifacts' },
        { from: 'commit', to: 'archive' },
        { from: 'layers', to: 'live' },
        { from: 'artifacts', to: 'files' },
        { from: 'archive', to: 'snapshots', label: 'moves committed files' },
        { from: 'associate', to: 'snapshots', dashed: true },
      ],
    },
    planned: {
      lanes: [
        'Agent (MCP)',
        'Web app',
        'Porcelain server',
        'Storage, Git and the disk',
      ],
      nodes: [
        {
          id: 'publish',
          lane: 0,
          kind: 'actor',
          label: 'publish_review · read_review',
          detail:
            'Summary HTML, an optional Before/After diagram and the layers in one call, with the revision it last saw',
          change: 'new',
        },
        {
          id: 'skill',
          lane: 0,
          kind: 'component',
          label: 'Agent skill',
          detail: 'How to write layers, plus a design guide for the summary',
          change: 'new',
        },
        {
          id: 'summary',
          lane: 1,
          kind: 'actor',
          label: 'Summary',
          detail:
            'The agent’s HTML, shown first; Summary | Graph switch with the Before/After diagram; boxes and #layer-N links open layers',
          change: 'new',
        },
        {
          id: 'layer',
          lane: 1,
          kind: 'actor',
          label: 'Layer',
          detail:
            'Lanes, then steps: label, title, explanation, code (a diff if changed); a Graph built from the steps; comment on a file or lines; tick when reviewed',
          change: 'changed',
        },
        {
          id: 'dot',
          lane: 1,
          kind: 'actor',
          label: 'Sidebar dot',
          detail:
            'Green: review ready · hollow green: all reviewed, ready to commit',
          change: 'new',
        },
        {
          id: 'link',
          lane: 2,
          kind: 'component',
          label: 'Summary link',
          detail:
            'Sandbox header like T3 Code: blank identity, scripts, CDNs and fonts allowed; up to 10 MB',
          change: 'new',
        },
        {
          id: 'reviewSvc',
          lane: 2,
          kind: 'component',
          label: 'Review',
          detail:
            'Whole replace with a revision; read once on open, then “not modified”',
          change: 'changed',
        },
        {
          id: 'pointers',
          lane: 2,
          kind: 'component',
          label: 'Code pointers and coverage',
          detail:
            'Re-finds each step; lists changed lines no step explains; folds committed steps',
          change: 'new',
        },
        {
          id: 'snapshots',
          lane: 2,
          kind: 'component',
          label: 'Per-commit snapshots',
          detail: 'Deferred; History shows plain commit diffs',
          change: 'removed',
        },
        {
          id: 'store',
          lane: 3,
          kind: 'storage',
          label: 'Latest review per worktree',
          detail: 'Summary, layers and layer marks in SQLite',
          change: 'changed',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git diff · files on disk',
          detail: 'Changed lines and the code each pointer names',
        },
      ],
      edges: [
        { from: 'skill', to: 'publish', dashed: true },
        { from: 'publish', to: 'reviewSvc' },
        {
          from: 'pointers',
          to: 'publish',
          label: 'gaps and broken pointers',
          dashed: true,
        },
        { from: 'summary', to: 'link' },
        { from: 'layer', to: 'reviewSvc', label: 'on open' },
        { from: 'layer', to: 'pointers' },
        { from: 'dot', to: 'pointers', label: 'stale or reviewed' },
        { from: 'link', to: 'store' },
        { from: 'reviewSvc', to: 'store' },
        { from: 'pointers', to: 'git' },
      ],
    },
  },
  {
    area: 'comments',
    title: 'Comments follow the code',
    notion: 'https://app.notion.com/p/3df4ccb1d6b8819b95b0e7d2783ca7fa',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Comments use the same code pointer as review steps: they move with the code and follow renames.',
      'When the code is gone the thread shows as Outdated, with a copy of the lines as they were when commented.',
      'Open threads never disappear or resolve on their own; committed or outdated ones stay listed until resolved; resolved ones hide behind “Show resolved”.',
      'A general thread for the whole worktree, besides file and line comments.',
      'Writes go straight to SQLite, not through the shared queue: a commit hook never blocks posting.',
      'No Git after a comment: the dot and counts come from the database and update on the spot; threads are indexed by worktree.',
      'One “seen up to” marker per thread, shared by all devices, drives the yellow dot.',
      'The app picks thread and message IDs, so a retry never duplicates; messages become their own rows.',
      'list_comments returns only what waits for the agent unless asked for everything; nothing is pushed to agents.',
      'Bodies are Markdown, never raw HTML.',
    ],
    current: {
      lanes: ['Web app and agents', 'Porcelain server', 'Storage and Git'],
      nodes: [
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Reviewer in the web',
          detail:
            'Discussion under a file header in Files and Changes; plain text',
        },
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Agent over MCP',
          detail: 'List, create, reply, resolve, when you tell it to read',
        },
        {
          id: 'badge',
          lane: 0,
          kind: 'actor',
          label: 'Sidebar counts',
          problem:
            'Every comment write refetches the worktree summary: 13+ Git processes for a count.',
        },
        {
          id: 'read',
          lane: 1,
          kind: 'component',
          label: 'List threads',
          detail: 'SQLite only, skips the queue',
        },
        {
          id: 'write',
          lane: 1,
          kind: 'component',
          label: 'Create, reply, resolve',
          problem:
            'Waits in the shared queue behind Git work; a commit hook can take 2 minutes.',
        },
        {
          id: 'anchor',
          lane: 1,
          kind: 'component',
          label: 'Anchor stored as sent',
          problem:
            'Never checked or moved: lines drift, renames lose threads, older-version threads are hidden.',
        },
        {
          id: 'summary',
          lane: 1,
          kind: 'component',
          label: 'Worktree summary',
          detail: 'Status or every diff, just to count open threads',
        },
        {
          id: 'table',
          lane: 2,
          kind: 'storage',
          label: 'comment_threads',
          detail: 'One JSON blob per thread, rewritten on every reply',
          problem:
            'No index by worktree; a retry after a dropped response duplicates.',
        },
        { id: 'git', lane: 2, kind: 'component', label: 'Git' },
      ],
      edges: [
        { from: 'web', to: 'write' },
        { from: 'agent', to: 'write' },
        { from: 'web', to: 'read' },
        { from: 'write', to: 'anchor' },
        { from: 'anchor', to: 'table' },
        { from: 'read', to: 'table' },
        { from: 'badge', to: 'summary', label: 'after every write' },
        { from: 'summary', to: 'git' },
        { from: 'summary', to: 'table', label: 'count', dashed: true },
      ],
    },
    planned: {
      lanes: ['Web app and agents', 'Porcelain server', 'Storage and the disk'],
      nodes: [
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Reviewer',
          detail:
            'Comment on a file, lines from any step, or the whole worktree; Markdown; Show resolved',
          change: 'changed',
        },
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Agent over MCP',
          detail:
            'list_comments returns what waits for the agent; nothing pushed',
          change: 'changed',
        },
        {
          id: 'dot',
          lane: 0,
          kind: 'actor',
          label: 'Sidebar dot',
          detail:
            'Yellow: the agent replied and you have not seen it; updated on the spot',
          change: 'changed',
        },
        {
          id: 'write',
          lane: 1,
          kind: 'component',
          label: 'Create, reply, resolve',
          detail:
            'Straight to SQLite, no queue; the app picks IDs, so retries never duplicate',
          change: 'changed',
        },
        {
          id: 'follow',
          lane: 1,
          kind: 'component',
          label: 'Comments follow the code',
          detail:
            'Same pointer as review steps; renames followed; Outdated keeps the lines as they were',
          change: 'new',
        },
        {
          id: 'seen',
          lane: 1,
          kind: 'component',
          label: 'Seen markers',
          detail: 'One per thread, shared by all your devices',
          change: 'new',
        },
        {
          id: 'threads',
          lane: 2,
          kind: 'storage',
          label: 'Threads and messages',
          detail:
            'Messages as rows, indexed by worktree; open threads never resolve on their own',
          change: 'changed',
        },
        {
          id: 'disk',
          lane: 2,
          kind: 'component',
          label: 'Files on disk · git status',
          detail: 'Where the code is now; renames',
        },
      ],
      edges: [
        { from: 'web', to: 'write' },
        { from: 'agent', to: 'write' },
        { from: 'web', to: 'follow', label: 'where is it now?' },
        { from: 'dot', to: 'seen', label: 'unseen agent replies' },
        { from: 'write', to: 'threads' },
        { from: 'seen', to: 'threads' },
        { from: 'follow', to: 'threads' },
        { from: 'follow', to: 'disk' },
      ],
    },
  },
  {
    area: 'artifacts',
    title: 'Dropped: the review summary replaces them',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881fd90a4f0f4530ebef0',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'publish_artifact, the artifact routes, the artifacts table and the web’s artifact documents are removed.',
      'The summary HTML, published with the review, covers reports; screenshots are embedded in it.',
      'Old handoffs are dropped with the table, without migration.',
      'The summary lives in SQLite with the review: only the latest, 10 MB per worktree, no server-wide quota; deleted 30 days after its worktree disappears.',
      'Rule for the whole server: only Git work goes through the queue; database-only work runs directly.',
      'Deferred: review attachments (files linked from the summary) if a need appears.',
    ],
    current: {
      lanes: ['Agent and web', 'Porcelain server', 'Storage'],
      nodes: [
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Agent: publish_artifact',
          detail: 'handoff.md, handoff.html, anything else',
        },
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Handoff tab and sidebar documents',
          problem:
            'Shows the oldest handoff; republishing adds a copy and nothing can delete.',
        },
        {
          id: 'queue',
          lane: 1,
          kind: 'component',
          label: 'Operations queue',
          problem:
            'Upload, list and read wait behind Git work, though none touches Git.',
        },
        {
          id: 'routes',
          lane: 1,
          kind: 'component',
          label: 'Artifact routes',
          detail:
            'Upload, list, read, delete (nothing calls delete); strict UTF-8, JSON only',
        },
        {
          id: 'table',
          lane: 2,
          kind: 'storage',
          label: 'artifacts table',
          detail: 'Content in SQLite rows',
          problem:
            'One global quota (256 files, 16 MiB) counting vanished worktrees; full means every upload fails.',
        },
      ],
      edges: [
        { from: 'agent', to: 'queue' },
        { from: 'web', to: 'queue', label: 'list, then read' },
        { from: 'queue', to: 'routes' },
        { from: 'routes', to: 'table' },
      ],
    },
    planned: {
      lanes: ['Agent and web', 'Porcelain server', 'Storage'],
      nodes: [
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Agent: publish_review',
          detail: 'The summary HTML travels with the review (section 4)',
          change: 'changed',
        },
        {
          id: 'web',
          lane: 0,
          kind: 'actor',
          label: 'Summary tab',
          detail: 'Loaded from its own link',
          change: 'changed',
        },
        {
          id: 'review',
          lane: 1,
          kind: 'component',
          label: 'Review',
          detail: 'Database only, so it skips the queue',
          change: 'changed',
        },
        {
          id: 'routes',
          lane: 1,
          kind: 'component',
          label: 'Artifact routes and publish_artifact',
          change: 'removed',
        },
        {
          id: 'store',
          lane: 2,
          kind: 'storage',
          label: 'Latest review per worktree',
          detail:
            'Summary up to 10 MB; no global quota; removed 30 days after its worktree',
          change: 'changed',
        },
        {
          id: 'table',
          lane: 2,
          kind: 'storage',
          label: 'artifacts table',
          detail: 'Dropped without migration',
          change: 'removed',
        },
      ],
      edges: [
        { from: 'agent', to: 'review' },
        { from: 'web', to: 'review' },
        { from: 'review', to: 'store' },
      ],
    },
  },
  {
    area: 'files',
    title: 'No Git per read, folders on demand, live updates',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881429124ec32ca167e5d',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Reading a file costs no Git: the worktree identity is one stat of its Git folder (the ID is derived from it); path safety stays.',
      'Folders load when opened (one directory read, about one Git call for ignored entries); quick open is one git ls-files.',
      'The whole-tree walk and the double listing go away; ignored folders like node_modules show dimmed and load only when opened.',
      'A live channel replaces polling: one WebSocket per app with change notices; watchers on open worktrees and on each project’s Git folder.',
      'Saving refreshes only that file and the list of changes.',
      'HTML files open from their own signed link with the summary’s sandbox; sibling assets load directly.',
      'Files stays a light file manager: edit, create, move, delete to the system trash, including ignored files like .env.',
    ],
    current: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Checks around every read',
        'Git and the disk',
      ],
      nodes: [
        {
          id: 'open',
          lane: 0,
          kind: 'actor',
          label: 'Open file, every 3 s',
          problem: 'Polls through the Git queue at full cost.',
        },
        {
          id: 'tree',
          lane: 0,
          kind: 'actor',
          label: 'Files tree',
          problem:
            'Loads a whole-tree listing and per-folder listings; both reload on every focus.',
        },
        {
          id: 'save',
          lane: 0,
          kind: 'actor',
          label: 'Save, create, move, trash',
          problem: 'Reloads every query of the worktree afterwards.',
        },
        {
          id: 'preview',
          lane: 0,
          kind: 'actor',
          label: 'HTML preview',
          problem: 'One API request per image or script, up to 64.',
        },
        {
          id: 'reads',
          lane: 1,
          kind: 'component',
          label: 'File, folder, tree and asset reads',
          detail: 'Path safety: no symlinks out, change-during-read detection',
        },
        {
          id: 'walk',
          lane: 1,
          kind: 'component',
          label: 'Whole-tree walk',
          problem:
            'Re-checks every parent of every path: hundreds of thousands of syscalls for 50,000 paths.',
        },
        {
          id: 'identity',
          lane: 2,
          kind: 'component',
          label: 'List every worktree, before and after',
          problem:
            '4 + 4 per worktree Git processes per read: 28 with 6 worktrees.',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git worktree list · rev-parse ×2 per worktree',
        },
        { id: 'disk', lane: 3, kind: 'storage', label: 'Worktree files' },
      ],
      edges: [
        { from: 'open', to: 'reads' },
        { from: 'tree', to: 'reads' },
        { from: 'tree', to: 'walk' },
        { from: 'preview', to: 'reads', label: 'per asset' },
        { from: 'save', to: 'reads', label: 'reload all', dashed: true },
        { from: 'reads', to: 'identity' },
        { from: 'walk', to: 'identity' },
        { from: 'identity', to: 'git' },
        { from: 'reads', to: 'disk' },
      ],
    },
    planned: {
      lanes: [
        'Web app',
        'Porcelain server',
        'Checked cheaply',
        'Git and the disk',
      ],
      nodes: [
        {
          id: 'open',
          lane: 0,
          kind: 'actor',
          label: 'Open file',
          detail: 'Reloads only when a notice says it changed',
          change: 'changed',
        },
        {
          id: 'tree',
          lane: 0,
          kind: 'actor',
          label: 'Files tree',
          detail: 'Folders load when opened; ignored ones dimmed; quick open',
          change: 'changed',
        },
        {
          id: 'edit',
          lane: 0,
          kind: 'actor',
          label: 'Edit, create, move, delete',
          detail:
            'Light file manager, .env included; reloads only that file and the changes',
          change: 'changed',
        },
        {
          id: 'preview',
          lane: 0,
          kind: 'actor',
          label: 'HTML preview',
          detail: 'Own signed link, summary sandbox; siblings load directly',
          change: 'changed',
        },
        {
          id: 'live',
          lane: 1,
          kind: 'transport',
          label: 'Live channel',
          detail: 'One WebSocket per app: “these files changed”',
          change: 'new',
        },
        {
          id: 'reads',
          lane: 1,
          kind: 'component',
          label: 'File and folder reads',
          detail: 'Path safety kept; no Git queue',
          change: 'changed',
        },
        {
          id: 'watch',
          lane: 1,
          kind: 'component',
          label: 'Watchers',
          detail:
            'Open worktrees (ignored folders skipped) and each project’s Git folder; bursts grouped',
          change: 'new',
        },
        {
          id: 'identity',
          lane: 2,
          kind: 'component',
          label: 'Identity: one stat',
          detail: 'The worktree ID is derived from its Git folder’s identity',
          change: 'changed',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git ls-files · check-ignore',
          detail: 'Quick open; ignored entries of an opened folder',
        },
        {
          id: 'disk',
          lane: 3,
          kind: 'storage',
          label: 'Worktree files and Git folder',
        },
      ],
      edges: [
        { from: 'live', to: 'open', label: 'notice' },
        { from: 'open', to: 'reads' },
        { from: 'tree', to: 'reads' },
        { from: 'edit', to: 'reads' },
        { from: 'preview', to: 'reads' },
        { from: 'watch', to: 'live' },
        { from: 'reads', to: 'identity' },
        { from: 'reads', to: 'git', label: 'per folder' },
        { from: 'identity', to: 'disk' },
        { from: 'watch', to: 'disk' },
      ],
    },
  },
  {
    area: 'history',
    title: 'One Git call per page, lazy commits, live updates',
    notion: 'https://app.notion.com/p/3df4ccb1d6b88156bfddcba95b1b9982',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'A page of 50 commits is one git log (about 1–2 processes instead of about 64); guards once per request; the Git version read once at startup.',
      'The next page is “50 commits before the last one shown”: no signing key, survives restarts, no re-walk; a rewritten history restarts from the top.',
      'Live: new commits slide in at the top; a rewrite reloads from the top; nothing reloads on focus.',
      'A commit opens like Changes: its file list first, each diff as it scrolls into view; no 1 MB wall.',
      'One Git runner with one set of rules replaces the three executors.',
      'Per-commit review layers are removed (section 4).',
    ],
    current: {
      lanes: ['Web app', 'Porcelain server', 'Guards', 'Git'],
      nodes: [
        {
          id: 'list',
          lane: 0,
          kind: 'actor',
          label: 'History list, infinite scroll',
          problem: 'Window focus reloads every loaded page, one after another.',
        },
        {
          id: 'commit',
          lane: 0,
          kind: 'actor',
          label: 'Commit view',
          detail: 'Changes and archived layers',
        },
        {
          id: 'page',
          lane: 1,
          kind: 'component',
          label: 'Page of commits',
          detail: 'Signed cursor; key lives as long as the process',
          problem:
            'One cat-file per commit, serially; every page re-walks from the tip: about 64 processes.',
        },
        {
          id: 'inspect',
          lane: 1,
          kind: 'component',
          label: 'Inspect a commit',
          problem: 'Every diff at once, capped at 1 MB: big commits fail.',
        },
        {
          id: 'executor',
          lane: 1,
          kind: 'component',
          label: 'History executor',
          detail: 'The third way of running Git, with its own rules',
        },
        {
          id: 'guard',
          lane: 2,
          kind: 'component',
          label: 'Before and after',
          problem:
            '3 rev-parse + git --version, twice: 8 processes per request.',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'rev-list · cat-file per commit · diff',
        },
      ],
      edges: [
        { from: 'list', to: 'page' },
        { from: 'commit', to: 'inspect' },
        { from: 'page', to: 'executor' },
        { from: 'inspect', to: 'executor' },
        { from: 'executor', to: 'guard' },
        { from: 'executor', to: 'git' },
      ],
    },
    planned: {
      lanes: ['Web app', 'Porcelain server', 'Git'],
      nodes: [
        {
          id: 'list',
          lane: 0,
          kind: 'actor',
          label: 'History list',
          detail: 'New commits slide in at the top; no reload on focus',
          change: 'changed',
        },
        {
          id: 'commit',
          lane: 0,
          kind: 'actor',
          label: 'Commit view',
          detail: 'File list first, diffs as they scroll into view',
          change: 'changed',
        },
        {
          id: 'live',
          lane: 1,
          kind: 'transport',
          label: 'Live channel',
          detail: '“The branch moved”',
          change: 'new',
        },
        {
          id: 'page',
          lane: 1,
          kind: 'component',
          label: 'Page of commits',
          detail:
            '50 before the last commit shown; restarts from the top after a rewrite',
          change: 'changed',
        },
        {
          id: 'inspect',
          lane: 1,
          kind: 'component',
          label: 'Commit files and diffs',
          detail: 'Same pieces as Changes',
          change: 'changed',
        },
        {
          id: 'runner',
          lane: 1,
          kind: 'component',
          label: 'One Git runner',
          detail:
            'One set of rules for every Git call; guards once per request',
          change: 'changed',
        },
        {
          id: 'git',
          lane: 2,
          kind: 'component',
          label: 'git log (one per page) · git diff',
          detail: 'About 1–2 processes per page',
        },
      ],
      edges: [
        { from: 'live', to: 'list', label: 'notice' },
        { from: 'list', to: 'page' },
        { from: 'commit', to: 'inspect' },
        { from: 'page', to: 'runner' },
        { from: 'inspect', to: 'runner' },
        { from: 'runner', to: 'git' },
      ],
    },
  },
  {
    area: 'git-actions',
    title: 'One step with targeted checks, never locked',
    notion: 'https://app.notion.com/p/3df4ccb1d6b88161979bdce3cc3a5f67',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'One request per action; the server checks only what the action depends on: commit files against the fingerprints you saw, the branch and upstream for fetch, pull and push.',
      'No whole-tree hashing: the 10,000-file limit and the double inspection go away.',
      'Action IDs keep retries safe; records are deleted after 30 days; “busy?” looks only at running actions.',
      'A crash marks the action interrupted and shows Git’s state once; the project is never locked.',
      'Progress and completion over the live channel; only what changed reloads.',
      'Commit drafts read only the committed files’ diffs; the model list never waits; closing cancels.',
      'One lane per repository: projects never wait for each other.',
      'New actions: discard a file or hunk (restorable), amend (warns if pushed), switch and create branch.',
    ],
    current: {
      lanes: ['Web app', 'Porcelain server', 'Inspection', 'Git and the disk'],
      nodes: [
        {
          id: 'menu',
          lane: 0,
          kind: 'actor',
          label: 'Git menu and commit form',
          detail: 'Prepare, confirm, execute',
          problem:
            'Polls every 500 ms; afterwards reloads every worktree of the project.',
        },
        {
          id: 'prepare',
          lane: 1,
          kind: 'component',
          label: 'Prepare',
          detail: 'Stores a fingerprint of the whole state',
        },
        {
          id: 'execute',
          lane: 1,
          kind: 'component',
          label: 'Execute',
          detail: 'Receipt, request ID; runs on the shared queue',
          problem: 'A restart mid-action locks the project forever.',
        },
        {
          id: 'draft',
          lane: 1,
          kind: 'component',
          label: 'Commit draft',
          problem:
            'About 76 Git processes and three full reads before the CLI; the model list waits behind it.',
        },
        {
          id: 'inspect',
          lane: 2,
          kind: 'component',
          label: 'Inspect everything',
          detail: 'About 21–27 Git processes',
          problem:
            'Reads every working file; over 10,000 files or 32 MB, no action runs at all.',
        },
        {
          id: 'receipts',
          lane: 3,
          kind: 'storage',
          label: 'Receipts and preparations',
          problem: 'Never pruned; every action scans them all.',
        },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'Git and every working file',
        },
      ],
      edges: [
        { from: 'menu', to: 'prepare' },
        { from: 'menu', to: 'execute', label: 'confirm' },
        { from: 'menu', to: 'draft' },
        { from: 'prepare', to: 'inspect' },
        { from: 'execute', to: 'inspect', label: 'again' },
        { from: 'draft', to: 'inspect', label: '×3' },
        { from: 'execute', to: 'receipts' },
        { from: 'inspect', to: 'git' },
      ],
    },
    planned: {
      lanes: ['Web app', 'Porcelain server', 'Git'],
      nodes: [
        {
          id: 'menu',
          lane: 0,
          kind: 'actor',
          label: 'Git menu and commit form',
          detail:
            'One request after the confirm dialog; discard, amend, switch and create branch added',
          change: 'changed',
        },
        {
          id: 'live',
          lane: 1,
          kind: 'transport',
          label: 'Live channel',
          detail: 'Running, progress lines, done',
          change: 'new',
        },
        {
          id: 'action',
          lane: 1,
          kind: 'component',
          label: 'Run an action',
          detail:
            'Targeted check first: “changed since you looked”; action ID for safe retries',
          change: 'changed',
        },
        {
          id: 'lanes',
          lane: 1,
          kind: 'component',
          label: 'One lane per repository',
          detail:
            'Projects never wait for each other; a crash marks the action interrupted, never locks',
          change: 'changed',
        },
        {
          id: 'draft',
          lane: 1,
          kind: 'component',
          label: 'Commit draft',
          detail: 'Only the committed files’ diffs; cancel on close',
          change: 'changed',
        },
        {
          id: 'git',
          lane: 2,
          kind: 'component',
          label: 'Git',
          detail: 'The action’s own commands, plus hooks',
        },
        {
          id: 'records',
          lane: 2,
          kind: 'storage',
          label: 'Action records',
          detail: 'Deleted after 30 days',
          change: 'changed',
        },
      ],
      edges: [
        { from: 'menu', to: 'action' },
        { from: 'menu', to: 'draft' },
        { from: 'action', to: 'lanes' },
        { from: 'lanes', to: 'git' },
        { from: 'action', to: 'records' },
        { from: 'live', to: 'menu', label: 'progress' },
      ],
    },
  },
  {
    area: 'mcp',
    title: 'Six tools through porcelain mcp',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881a69ad6e24c4356792e',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Agents connect only with porcelain mcp through the local socket; /mcp is removed from HTTP.',
      'Tools resolve the worktree from the agent’s folder; inventory is removed.',
      'git_status, review_evidence and read_file are removed: the agent has its own Git and files; publish_review checks its work.',
      'Six tools: publish_review, read_review, list_comments, create_comment, reply_to_comment, resolve_comment.',
      'The MCP server serves the agent guide (layers, summary design, comments) itself.',
      'Errors tell the agent its next step; tests call every tool through the real command.',
    ],
    current: {
      lanes: [
        'Agents',
        'How they connect',
        'Porcelain server',
        'Git and storage',
      ],
      nodes: [
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Claude Code, Codex',
          detail: 'Admin token in the MCP config',
        },
        {
          id: 'http',
          lane: 1,
          kind: 'transport',
          label: 'POST /mcp over HTTP',
          detail: 'Bearer required, browsers refused, new server per request',
        },
        {
          id: 'find',
          lane: 2,
          kind: 'component',
          label: 'inventory',
          detail: 'The agent picks its worktree by ID',
        },
        {
          id: 'reads',
          lane: 2,
          kind: 'component',
          label: 'git_status · review_evidence · read_file',
          problem:
            'Git-heavy, on the reviewer’s queue: agents and you delay each other.',
        },
        {
          id: 'writes',
          lane: 2,
          kind: 'component',
          label: 'Comments, layers, artifacts',
          detail: 'replace_layers, publish_artifact, four comment tools',
        },
        { id: 'git', lane: 3, kind: 'component', label: 'Git' },
        { id: 'db', lane: 3, kind: 'storage', label: 'SQLite' },
      ],
      edges: [
        { from: 'agent', to: 'http' },
        { from: 'http', to: 'find' },
        { from: 'http', to: 'reads' },
        { from: 'http', to: 'writes' },
        { from: 'reads', to: 'git' },
        { from: 'writes', to: 'db' },
      ],
    },
    planned: {
      lanes: [
        'Agents',
        'How they connect',
        'Porcelain server',
        'Git and storage',
      ],
      nodes: [
        {
          id: 'agent',
          lane: 0,
          kind: 'actor',
          label: 'Claude Code, Codex',
          detail: 'Their own shell, Git and files; no secrets in their config',
          change: 'changed',
        },
        {
          id: 'cmd',
          lane: 1,
          kind: 'transport',
          label: 'porcelain mcp',
          detail: 'Runs in the agent’s folder; talks to the local socket',
          change: 'new',
        },
        {
          id: 'guide',
          lane: 2,
          kind: 'component',
          label: 'Agent guide',
          detail:
            'Served with the connection: layers, summary design, comments',
          change: 'new',
        },
        {
          id: 'review',
          lane: 2,
          kind: 'component',
          label: 'publish_review · read_review',
          detail:
            'Returns gaps and broken pointers; errors say what to do next',
          change: 'changed',
        },
        {
          id: 'comments',
          lane: 2,
          kind: 'component',
          label: 'Comment tools',
          detail: 'list (what waits for the agent), create, reply, resolve',
          change: 'changed',
        },
        {
          id: 'removed',
          lane: 2,
          kind: 'component',
          label:
            'inventory · git_status · review_evidence · read_file · publish_artifact',
          change: 'removed',
        },
        { id: 'db', lane: 3, kind: 'storage', label: 'SQLite' },
        {
          id: 'git',
          lane: 3,
          kind: 'component',
          label: 'git diff',
          detail: 'Only to check a published review',
        },
      ],
      edges: [
        { from: 'agent', to: 'cmd' },
        { from: 'cmd', to: 'guide' },
        { from: 'cmd', to: 'review' },
        { from: 'cmd', to: 'comments' },
        { from: 'review', to: 'db' },
        { from: 'review', to: 'git', label: 'coverage' },
        { from: 'comments', to: 'db' },
      ],
    },
  },
  {
    area: 'lifecycle',
    title: 'Lanes per repository, a Linux service, budgets enforced',
    notion: 'https://app.notion.com/p/3df4ccb1d6b881138797ec25468fad0e',
    decidedOn: '2026-09-18',
    reviewedOn: '2026-09-18',
    changes: [
      'Two ways to get Porcelain: an npm package (service on any Linux with systemd, macOS via launchd) or the Electron app hosting a server.',
      'service install | status | update | uninstall, like T3 Code; updates back up the database and refuse downgrades.',
      'One lane per repository: reads side by side (about 4), Git actions one at a time, database work never queues.',
      'Deadlines count from the start of the work; cancelled or disconnected requests stop their work.',
      'Startup listens right away; a slow repository only shows as unavailable.',
      'The local socket replaces server.lock: a crash never needs manual cleanup.',
      'Live channel housekeeping: heartbeat, automatic reconnect, watchers stop when unused.',
      'Real migrations from now on; your data carries over.',
      'Code organized by area, like this Map, as each area is rewritten.',
      'The lab’s measurements are the quality path: Git-process budgets in every spec run, pnpm bench:server on realistic playgrounds, the lab committed when the rewrite starts.',
    ],
    current: {
      lanes: ['Start and stop', 'Queues', 'Git and storage'],
      nodes: [
        {
          id: 'start',
          lane: 0,
          kind: 'actor',
          label: 'pnpm serve from a working tree',
          detail: 'Token, server.lock, migrate, recover, rescan, then listen',
          problem:
            'A hung repository fails the rescan and the server exits; a crash leaves server.lock for manual cleanup.',
        },
        {
          id: 'ops',
          lane: 1,
          kind: 'component',
          label: 'One operations queue',
          detail: 'Almost everything, one at a time, 30 s deadline',
          problem:
            'Head-of-line blocking across projects; the deadline counts queue wait; abandoned requests keep running.',
        },
        {
          id: 'side',
          lane: 1,
          kind: 'component',
          label: 'Discovery · browsing · summaries · drafting',
          detail: 'Four more single-lane runners',
        },
        {
          id: 'executors',
          lane: 2,
          kind: 'component',
          label: 'Four Git executors',
          problem:
            'Three identity checks answer the same question at three prices.',
        },
        {
          id: 'db',
          lane: 2,
          kind: 'storage',
          label: 'SQLite',
          detail: 'Baseline may be regenerated (wipes data)',
        },
      ],
      edges: [
        { from: 'start', to: 'ops', label: 'rescan' },
        { from: 'ops', to: 'executors' },
        { from: 'side', to: 'executors' },
        { from: 'ops', to: 'db' },
      ],
    },
    planned: {
      lanes: ['How it runs', 'Work', 'Quality path', 'Git and storage'],
      nodes: [
        {
          id: 'service',
          lane: 0,
          kind: 'actor',
          label: 'npm package as a service',
          detail:
            'systemd user service with lingering on any Linux; launchd on macOS; install, status, update, uninstall',
          change: 'new',
        },
        {
          id: 'electron',
          lane: 0,
          kind: 'actor',
          label: 'Electron app hosting a server',
          change: 'new',
        },
        {
          id: 'socket',
          lane: 0,
          kind: 'storage',
          label: 'Local socket',
          detail: '“Already running?” check; replaces server.lock',
          change: 'new',
        },
        {
          id: 'lanes',
          lane: 1,
          kind: 'component',
          label: 'One lane per repository',
          detail:
            'Reads side by side, actions one at a time; deadline from start; cancelled work stops',
          change: 'changed',
        },
        {
          id: 'direct',
          lane: 1,
          kind: 'component',
          label: 'Database work',
          detail: 'Runs directly, never queues',
          change: 'changed',
        },
        {
          id: 'live',
          lane: 1,
          kind: 'transport',
          label: 'Live channel',
          detail: 'Heartbeat, reconnect, watchers stop when unused',
          change: 'new',
        },
        {
          id: 'budgets',
          lane: 2,
          kind: 'component',
          label: 'Budgets in every spec run',
          detail: 'Git processes per operation, from the tracing channels',
          change: 'new',
        },
        {
          id: 'bench',
          lane: 2,
          kind: 'component',
          label: 'pnpm bench:server',
          detail: 'This lab’s bench on the app and monorepo playgrounds',
          change: 'new',
        },
        {
          id: 'runner',
          lane: 3,
          kind: 'component',
          label: 'One Git runner',
          change: 'changed',
        },
        {
          id: 'db',
          lane: 3,
          kind: 'storage',
          label: 'SQLite',
          detail: 'Real migrations; data carries over',
          change: 'changed',
        },
      ],
      edges: [
        { from: 'service', to: 'socket' },
        { from: 'electron', to: 'socket' },
        { from: 'service', to: 'lanes', label: 'listens at once' },
        { from: 'lanes', to: 'runner' },
        { from: 'direct', to: 'db' },
        { from: 'budgets', to: 'lanes', dashed: true },
        { from: 'bench', to: 'lanes', dashed: true },
      ],
    },
  },
];

export const planFor = (area: string | undefined) =>
  plans.find((plan) => plan.area === area);
